### ISSUE TITLE
Start Here Primer

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#10]
Link to primer here: [Start Here](https://drive.google.com/open?id=12q28CfslRCow5YxC5DHkWx3S4hemefd5TDsECz2GC3o)

┆Issue is synchronized with this [Trello card](https://trello.com/c/Un5rYznL)

**Comment by lourdesvera** [comment]
We need to do another round of rejecting, responding, and editing

**Comment by Frijol** [comment]
We seem to have a complete draft of this primer, so closing
