### ISSUE TITLE
Purchase Mural.ly for EDGI?

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#106]
@lourdesvera what is the cost? What discussion is necessary? cc @saraannwylie @EDGI-Comms @crgreenleaf @calderEDJ

┆Issue is synchronized with this [Trello card](https://trello.com/c/p5h56dQp)

**Comment by Frijol** [comment]
Looks like it's $12/mo billed annually so $144 if we want it for the full year, or $16/month so if we want it for half a year that would be $96. I'm leaning toward annual because I suspect this tool will become useful EDGI-wide and we have $1700 budgeted EEW event supplies

**Comment by EDGI-Comms** [comment]
Is Mural.ly necessary now that we're designing the site on Figma? Seems like it might be good to limit platforms. Or we can save money and use google draw if there are suggestions for layouts of other pages? I can also just take a stab at continuing to lay the pages out on Figma and then ask for feedback/edits?

**Comment by Frijol** [comment]
Mural.ly is for post-it style collaboration, so kind of a different use case (planning to use for EEW events too). We have money for good tools so I think it's ok to use it!

Discusses Mural purchase in EDJ meeting yesterday & got the go-ahead but then Mural let me make a workspace for free so didn't purchase yet

**Comment by EDGI-Comms** [comment]
Ah okay! Thought it was just for the website.

**Comment by Frijol** [comment]
Closing issue because we discussed & decided to buy (even though I didn't need to buy it)

**Comment by Frijol** [comment]
Purchased!
