### ISSUE TITLE
Create EEW email in namecheap

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#107]
Create e-mail through Namecheap.

Info@Environmentalenforcementwatch.org ?

┆Issue is synchronized with this [Trello card](https://trello.com/c/Jpv5z4xs)

**Comment by lourdesvera** [comment]
trying to coordinate with Aparna to be online at the same time. I have the password but not 2FA

**Comment by lourdesvera** [comment]
Waiting for @lightandluck to come back from vaycay to get help on this issue. Namecheap server needs to be "basic DNS" to set up e-mail forwarding but it isn't, and I can't access the home page on Wordpress where I go to "mysites" and configure the e-mail forwarding. 

Bigger question- where is the hosting information on wordpress?

**Comment by lightandluck** [comment]
I've been documenting stuff about our website and how-to's in this folder: https://drive.google.com/drive/u/0/folders/13PvZjbzJkZbM9bcMwxraEQUzbD1B4-j9

**Comment by lourdesvera** [comment]
info@environmentalenforcementwatch.org was created! All e-mails are forwarded to environmentalenforcementwatch@gmail.com. Let me know if you want access to this account.
