### ISSUE TITLE
Finalize/clean up logo

### ISSUE THREAD

**Issue by calderEDJ** [edgi-govdata-archiving/EEW_Planning#109]
Circle back with Eli so he can clean up the winning logo (the current version is a low-res draft that I put together from the other designs

┆Issue is synchronized with this [Trello card](https://trello.com/c/pXwa9H0r)

**Comment by calderEDJ** [comment]
Eli just responded to my email from last week. They'll clean up the version we voted on and have a few more options based on Sara's suggestions

**Comment by lourdesvera** [comment]
@calderEDJ is this done?

**Comment by lourdesvera** [comment]
Out for vote
