### ISSUE TITLE
Congressional District Primer

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#11]
[Congressional district primer](https://drive.google.com/open?id=17fBEiAVdTJvPmO7ZRC86vfGKkfHMVMHkQnyMJOHqMjw)

┆Issue is synchronized with this [Trello card](https://trello.com/c/wzwOGQYu)

**Comment by Frijol** [comment]
Is there more that needs to be done here, or should we close this until there is a specific, resolvable need?

**Comment by ericnost** [comment]
Should we update this to reflect the fact that we now have one main notebook ("Cross-Program") that allows people to look at different geographies and different programs? We could keep it focused on Congressional Districts, but update some of the details to reflect changes to the notebook. We could ask @maalvikabhat to help out!

**Comment by maalvikabhat** [comment]
I could definitely suggest changes to this document to reflect that!

**Comment by shansen5** [comment]
Here's some thought I've been having along these lines:

A weakness of the notebooks is that they only give one step-by-step path through the analysis.  In the Cross Programs notebook we now have many data sets that can be requested for 4 different geographical areas.  This has a lot of value for the breadth of analyses that can be done in a single notebook.  A logical next step for a user would be to drill deeper into a particular data set:  This has identified CAA violation data for my county, now I'd like to see the ranked violators, see quantities of emissions and locate them in census blocks. 

If we try to answer many of those kinds of program-specific questions in the one Cross Program notebook it would quickly get unwieldy.  But it would be good to take advantage of the work done in Cross Program as a head start toward deeper analysis in other specialized notebooks.  

We could have the specialized notebooks pick up the data produced within Cross Program.  They could be constructed so as to read CSVs that are produced and continue their deeper analysis.  We might even put links to the specialized notebooks into Cross Program.
A danger of the specialized notebooks relying on the CSVs is their reliance on the format of the CSVs being produced by Cross Program.

**Comment by ericnost** [comment]
I like these ideas @shansen5. 

I agree that we really can't add any more code blocks to Cross-Program! However, I do think there are ways we can allow drilling deeper without adding too much more code. For instance, ranking facilities may not be that hard (?) as I have some code in the covid notebook for aggregating the selected data type by facility: https://github.com/edgi-govdata-archiving/ECHO-COVID19/blob/master/ECHO-COVID19.ipynb It would allow us to style the markers on the map (e.g. size of marker = # of violations). This would facilitate what already happens in the notebook - users selecting an individual facility to explore. For instance, they might choose the "worst" facility based on what the ranking/map showed them. 

But I love the idea of creating other, shorter, single purpose, more specialized notebooks that take output from Cross-Program and do things like:
- show state vs federal actions
- advanced visualization (with an R-based notebook?)
- environmental justice analysis
- etc.

@maalvikabhat I would say, if you have the time, please start suggesting edits to the Congressional District Primer to reflect what we have in the Cross-Program notebook now.

And let's continue talking about these more specialized spinoff notebooks...

**Comment by lourdesvera** [comment]
Closing this since we've put the congressional report how-tos in other primers
