### ISSUE TITLE
Preparing summary of ECHO Survey for EPA Staff

### ISSUE THREAD

**Issue by csellers9** [edgi-govdata-archiving/EEW_Planning#112]
Sorry given all the other stuff, but would really like to keep awareness of this, as we don't want to wait too long to get back to them.  Was Cole working on this?  others? @calderEDJ

┆Issue is synchronized with this [Trello card](https://trello.com/c/3gXRSnuv)

**Comment by calderEDJ** [comment]
yes, sorry I was working on this but it got lost in the shuffle. I'll finish it up today

**Comment by calderEDJ** [comment]
Here is the UX Difficulties summary from all three classes that participated, with response codes that probably need revising: https://docs.google.com/spreadsheets/d/1O3_HPnwTzPAgpaC6HokrlYl8Haxv1CHPj5_e2FGQacs/edit#gid=1815047088

**Comment by ericnost** [comment]
@calderEDJ Can we start a short Slides deck summarizing these results?

cc: @saraannwylie

**Comment by calderEDJ** [comment]
@ericnost I'll get started on those slides later today
