### ISSUE TITLE
Outline EEW Personnel and roles

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#114]
* [x] Decide who has which role
* [x] Finalize roles in this slide deck: https://docs.google.com/presentation/d/1hYUa9-09a4VlG2gEtXguSsry8Z82xQy5nwLCoi0cclA/edit
* [x] Enter roles in readme https://github.com/edgi-govdata-archiving/EEW_Planning/issues/92
* [x] add this information to onboarding process https://github.com/edgi-govdata-archiving/EEW_Planning/issues/89
* [x] Design roles and responsibilities document https://docs.google.com/presentation/d/1hYUa9-09a4VlG2gEtXguSsry8Z82xQy5nwLCoi0cclA/edit#slide=id.p
This is related to https://github.com/edgi-govdata-archiving/EEW_Planning/issues/92

┆Issue is synchronized with this [Trello card](https://trello.com/c/9ifQHkYm)

**Comment by lourdesvera** [comment]
Slides: https://docs.google.com/presentation/d/1hYUa9-09a4VlG2gEtXguSsry8Z82xQy5nwLCoi0cclA/edit

**Comment by lourdesvera** [comment]
Are these roles ready to enter into the readme?

**Comment by Frijol** [comment]
I think that would be great! And this is an excellent opportunity for a pull request/review process, we should ask each person mentioned to review their role
