### ISSUE TITLE
Create partnership outreach document

### ISSUE THREAD

**Issue by crgreenleaf** [edgi-govdata-archiving/EEW_Planning#116]
┆Issue is synchronized with this [Trello card](https://trello.com/c/73j8zjHK)

**Comment by saraannwylie** [comment]
Hi @crgreenleaf I started this document [here](https://docs.google.com/spreadsheets/d/1wsj5_c2FBynmB_tg2QUmWwDb6QzB-H3tHa5YgS81iNc/edit#gid=0)

**Comment by saraannwylie** [comment]
@crgreenleaf and I converged our outreach planning docs[ here](https://docs.google.com/spreadsheets/d/1CP-1j50xlkYOmduMkDwYr3DadhKEHhtw0MGT03Dxm0k/edit#gid=0)
