### ISSUE TITLE
Establish track workflow

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#117]
*  [x] complete event tracking sheet: https://docs.google.com/spreadsheets/d/1Z2rBoGqb_SXW6oAu12A6TCWEJGV1pk0YxL13P_Z5Wlw/edit?usp=drive_web&ouid=110602273190303993217 
* [x] fill in event tracking sheet with outcomes from Stonybrook event
* [x] Event flowchart
* [x] make sure everyone is on board

related to issue #188 
┆Issue is synchronized with this [Trello card](https://trello.com/c/h9zOhuk3)

**Comment by lourdesvera** [comment]
@calderEDJ @crgreenleaf can you help with this?

**Comment by lourdesvera** [comment]
Created a track workflow here: https://docs.google.com/drawings/d/1ORr30WC9_fZWFbMLvQ6D9IKw3Y1qzGcIAwgVhQURLB0/edit
![Event_Flow](https://user-images.githubusercontent.com/23300449/82915689-11e1fb00-9f3f-11ea-81a5-44ecdd889a19.jpg)

**Comment by lourdesvera** [comment]
@maalvikabhat can I add you to this task? @ericnost what do you think?

**Comment by ericnost** [comment]
@lourdesvera Can we link this to #172? They actually seem like the same thing, but it's something maybe all the interns should do given that it encompasses all 4 tracks. It's also not entirely clear to me what the ultimate purpose of the tracker is and exactly what needs to be done. At the very least, it needs to be slightly updated given that we are trying to centralize the notebooks to Cross-Program.
