### ISSUE TITLE
Design Roles and Responsibilities document

### ISSUE THREAD

**Issue by crgreenleaf** [edgi-govdata-archiving/EEW_Planning#120]
https://docs.google.com/presentation/d/1hYUa9-09a4VlG2gEtXguSsry8Z82xQy5nwLCoi0cclA/edit#slide=id.p

┆Issue is synchronized with this [Trello card](https://trello.com/c/2uPdPpq2)

**Comment by lourdesvera** [comment]
How does this differ from https://github.com/edgi-govdata-archiving/EEW_Planning/issues/92?

**Comment by lourdesvera** [comment]
Added this as a subtask to #92 and closing :-)
