### ISSUE TITLE
License notebooks

### ISSUE THREAD

**Issue by saraannwylie** [edgi-govdata-archiving/EEW_Planning#122]
Discuss licensing for notebooks and add licenses to notebooks...suggest creative commons, sticky, with attribution? Also non commerical?

--- 
(added later by @frijol:)

Add licensing to repos:
* [x] ECHO-CWA
* [ ] ECHO cross-program

┆Issue is synchronized with this [Trello card](https://trello.com/c/PUzS1uP1)

**Comment by saraannwylie** [comment]
More to discuss here? Add authorship following edgi protcol? Add EDGI logo?

**Comment by ericnost** [comment]
And add EEW logo.

**Comment by ericnost** [comment]
Circling back to this. In terms of licenses, we are already using GPL-3.0 for the repositories, and I think that covers the notebooks themselves. However, we should add that language to each of the notebooks.

In addition, it appears ECHO-CWA and ECHO-CrossProgram do not currently have licenses, so we should add them.

edgi-govdata-archiving/ECHO-Cross-Program/issues/16
(Actually, the license is written out, but no LICENSE file provided) 

I merged a branch from Kelsey that fixed ECHO-CWA.

Thoughts @Frijol @shansen5 ?

**Comment by Frijol** [comment]
I think you're 100% correct re what license they should have & I do think the licensing for the repo applies. I added checkboxes for licensing to the issue description.

Do you think it's necessary to stick a license header into the notebook itself? Sounds like we might be starting to want a template for notebooks.

I propose this issue can be closed by applying licenses to the two unlicensed repos & that we move the template discussion to this new issue: https://github.com/edgi-govdata-archiving/EEW_Planning/issues/130

**Comment by ericnost** [comment]
Hmm. So ECHO - Cross Program has a license, just no license file. Not sure how to add that @Frijol . I'm going to close this issue.

**Comment by Frijol** [comment]
oh, I'll add one!
