### ISSUE TITLE
Make a Sprint board for next week

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#123]
┆Issue is synchronized with this [Trello card](https://trello.com/c/oNCwWoOC)

**Comment by lourdesvera** [comment]
I made one here: https://github.com/edgi-govdata-archiving/EEW_Planning/projects/4?add_cards_query=is%3Aopen

I sort of like the review columns?

**Comment by Frijol** [comment]
Cool! Def worth trying new columns
