### ISSUE TITLE
Create a single source-of-truth list of the notebooks

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#125]
Someone make one source of truth for where the list of all the notebooks lives (don’t start from scratch, there are several pieces of it) and link there from all the others.

Currently there is a list in a doc, a spreadsheet, a readme, others? (Collect links in this issue that have parts of this info)

There should be just one place that all the others link to so we don't get out of sync.

cc @lourdesvera @ericnost @saraannwylie @csellers9 @shansen5 @calderEDJ

┆Issue is synchronized with this [Trello card](https://trello.com/c/qpXc3v0J)

**Comment by ericnost** [comment]
#124 

See also edgi-govdata-archiving/Environmental-Enforcement-Watch

**Comment by ericnost** [comment]
https://docs.google.com/spreadsheets/d/1Z2rBoGqb_SXW6oAu12A6TCWEJGV1pk0YxL13P_Z5Wlw/edit#gid=903191621
