### ISSUE TITLE
Design intern program

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#126]
This is a directory issue for designing a full intern program + discussing what components there are in the execution of an intern program. Here are components of the process I can think of

* [x] Hiring process https://github.com/edgi-govdata-archiving/EEW_Planning/issues/103
* [x] Onboarding process https://github.com/edgi-govdata-archiving/EEW_Planning/issues/89
* [x] Role definition https://github.com/edgi-govdata-archiving/EEW_Planning/issues/91
* [x] Management structure https://github.com/edgi-govdata-archiving/EEW_Planning/issues/90
* [x] Social support https://github.com/edgi-govdata-archiving/EEW_Planning/issues/148
* [x] End-of-summer wrap-up

Are more pieces needed?

┆Issue is synchronized with this [Trello card](https://trello.com/c/qtR37Pjx)

**Comment by lourdesvera** [comment]
I created a milestone that this relates to, "solid onboarding"

**Comment by Frijol** [comment]
ha, I also have a milestone for this, "Summer hires start". Should we merge?

**Comment by lourdesvera** [comment]
> ha, I also have a milestone for this, "Summer hires start". Should we merge?

Yeah, let's merge @Frijol . And for the offboarding, what should we make? an offboarding doc? reflections? Way to map out what's been done and next steps for the rest of the team moving forward?

**Comment by Frijol** [comment]
Might be a few components!
* They're doing an intro post together, could do an outro reflections post? (Might be nice for each to do their own that they could later ref)
* Would be really nice to have a celebration meeting
* Probably use Kevin's contractor offboarding session too

**Comment by Frijol** [comment]
Should we close this issue and open a few for end of summer?

**Comment by lourdesvera** [comment]
@Frijol Let's come up with a plan for this this week? Maybe do a mid-summer reflection during intern check-ins next week @saraannwylie @ericnost to guide the offboarding process?

**Comment by Frijol** [comment]
Did mid-summer reflections happen last week?

Thoughts re offboarding:
* Should have a celebration meeting as our last Tuesday meeting
* Exit interviews for each? (Trade around the last 1:1 so you don't interview a direct report?)
* Anything more? Or is that enough?
