### ISSUE TITLE
Make EDGI Organizational Chart 

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#132]
* [x] Create a chart that has an overview of EDGI working groups, people, and roles in google [draw](https://docs.google.com/drawings/d/1ZK_jFWq6o2VG--KEu-vHUE57NLHuWJD51jZ_kLRv9t0/edit)
* [x] Copy and paste into the EDGI [organizational chart slide deck](https://docs.google.com/drawings/d/1ZK_jFWq6o2VG--KEu-vHUE57NLHuWJD51jZ_kLRv9t0/edit) so that it can be updated easily and linked to in onboarding slide decks.

┆Issue is synchronized with this [Trello card](https://trello.com/c/sJvXoicu)

**Comment by Frijol** [comment]
The slide chart deck is the wrong link, where is the right one? @lourdesvera

**Comment by saraannwylie** [comment]
Made a draft here @lourdesvera @Frijol https://docs.google.com/drawings/d/1ZK_jFWq6o2VG--KEu-vHUE57NLHuWJD51jZ_kLRv9t0/edit

Just added to the diagram in the doc.

**Comment by lourdesvera** [comment]
charts here: https://app.mural.co/t/edgi7967/m/edgi7967/1591796344810/85038f0c63b311f8a61e25b9201e70f713657179

and here: 
https://docs.google.com/drawings/d/1ZK_jFWq6o2VG--KEu-vHUE57NLHuWJD51jZ_kLRv9t0/edit

**Comment by lourdesvera** [comment]
@EDGI-Comms @crgreenleaf can you review these?

**Comment by crgreenleaf** [comment]
Made some grammatical edits in the Mural. I love the graphic - I think it's a great way of visualizing these intersections. 

Some of the language in the Mural is a bit vague, can it be simplified or explained more? Would it benefit from some concrete working examples?
