### ISSUE TITLE
Register for ESIP summer meeting

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#136]
The usual approach is to reach out to a session coordinator and ask to talk in their session.
@saraannwylie suggests https://2020esipsummermeeting.sched.com/event/cItw/putting-air-quality-data-to-work-data-and-tools-to-understand-it

┆Issue is synchronized with this [Trello card](https://trello.com/c/4mFgwqNd)

**Comment by Frijol** [comment]
I'm meeting with the ESIP data stewardship team on Monday to get a better understanding of the submission process

**Comment by lourdesvera** [comment]
Let's do this. It wouldn't require much preparation on our ends. There are great folks at ESIP.

**Comment by Frijol** [comment]
Adding in your thoughts from Slack @lourdesvera 
> RE: the ESIP event, I think it would be really easy for us to present on the Jupyter notebooks. We already have presentations that can be tweaked and material to demo.https://2020esipsummermeeting.sched.com/event/cItw/putting-air-quality-data-to-work-data-and-tools-to-understand-it

**Comment by ericnost** [comment]
Agreed!

**Comment by Frijol** [comment]
I don't have the space to pursue this at the moment but I think it's a bit urgent. @saraannwylie do you / do you have a suggestion for who might take concrete next steps?

**Comment by calderEDJ** [comment]
Per the June 9th EEW meeting, I can take point on this and work with Kelsey on setting it up tomorrow

**Comment by Frijol** [comment]
@calderEDJ short story here is, I'm super unclear what the submission process is and whether/what is possible. I just sent an email to the organizers seeking some clarity there and will let you know what I learn

**Comment by calderEDJ** [comment]
@Frijol By the look of it, they do have a full program (https://2020esipsummermeeting.sched.com/). We have until July 1st to register with the video/poster. Should we get started on that today / next week?

**Comment by Frijol** [comment]
By "full program" I mean the leads of the particular session, in past ESIP meetings leaders have reserved space for community submissions. But I suspect all-digital is different, and the session leads have not gotten back to me, so let's proceed assuming that's not an option.

Re working on video/poster, I think that would be a good idea! Probably register ASAP (@saraannwylie what's needed for Cole to have approval for reimbursement?). Registration has a checkbox for whether you're planning to submit a poster or video.

**Comment by saraannwylie** [comment]
I sense we call concur that $40 is well worth it, so @calderEDJ go ahead and register, and we'll ask Aparna next week about reimbursing you?

**Comment by Frijol** [comment]
@calderEDJ feel free to close this once you have registered! I made a new issue for the actual making of the poster or video: https://github.com/edgi-govdata-archiving/EEW_Planning/issues/174

**Comment by calderEDJ** [comment]
Registration is complete!
