### ISSUE TITLE
EEW Primer Template

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#14]
[Primer Template](https://drive.google.com/open?id=1RmJews3gjNYY7umZjKzg6bfhbF3auFSwcVUHzMY1ke8)

┆Issue is synchronized with this [Trello card](https://trello.com/c/fq5spTjH)

**Comment by Frijol** [comment]
wait are we using Trello as well as a Kanban board here in Github? Seems like a lot.

Also, didn't you already make a template?

**Comment by Frijol** [comment]
Resolving, I'm pretty sure we have a template for primers
