### ISSUE TITLE
Meeting with Cynthia Giles

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/EEW_Planning#144]
### Meeting

- [x] Add questions to the list: https://docs.google.com/document/d/1XNUSvmjMLAaCPh81_whmYB-RHjKwqHAstdxSLP34Lac/edit#heading=h.ln1hp8wwafqo
- [x] Finish reviewing slides: https://docs.google.com/presentation/d/1FOkH1i4nWckiotvfOyZxj06RjL7God6Eyzqe8MqLhXE/edit#slide=id.g74f3589e8b_4_4
- [x] Practice presentation
- [x] Present

┆Issue is synchronized with this [Trello card](https://trello.com/c/WJdQ6Usz)

**Comment by saraannwylie** [comment]
I made a notes document to share thoughts on the background readings:
https://docs.google.com/document/d/1hW-L_jCDs9IG71h6HHlk4sCC9Rk_ZmuTDWG1JGMKE4Y/edit

**Comment by ericnost** [comment]
Well done all!
