### ISSUE TITLE
Develop website copy

### ISSUE THREAD

**Issue by calderEDJ** [edgi-govdata-archiving/EEW_Planning#145]
Landing/home page copy: https://docs.google.com/document/d/1Bde1qfxshfwk9y7S2NgJnpFm5VGLYzKuHOqucWjOdEs/edit?usp=sharing

About/partners page copy: https://docs.google.com/document/d/1y2asMEiGDwDZ5rsits1cK7W-UqVnxMNGXFIDVVWozlk/edit?usp=sharing

once copy is fully developed in the google docs -> review -> put on website -> put screenshot on [mural.ly](http://mural.ly/)

┆Issue is synchronized with this [Trello card](https://trello.com/c/aaIPetTp)

**Comment by calderEDJ** [comment]
Landing/homepage copy is ready for review: https://docs.google.com/document/d/1Bde1qfxshfwk9y7S2NgJnpFm5VGLYzKuHOqucWjOdEs/edit?usp=sharing

**Comment by calderEDJ** [comment]
About page copy ready is for review: https://docs.google.com/document/d/1y2asMEiGDwDZ5rsits1cK7W-UqVnxMNGXFIDVVWozlk/edit?usp=sharing

**Comment by calderEDJ** [comment]
@lourdesvera @saraannwylie @EDGI-Comms could you all make edits/comments when you get a chance?

**Comment by saraannwylie** [comment]
@calderEDJ @lourdesvera @EDGI-Comms taking 1st responder here to review copy

**Comment by saraannwylie** [comment]
Reviewed both, made comments, great start--follow up tomorrow?
