### ISSUE TITLE
Add availability to calendar

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/EEW_Planning#147]
As we onboard new interns, we need to keep track of all our schedules, similar to what EDGI coordinating committee has/had. 

Please use the existing EEW calendar to indicate your availability: https://calendar.google.com/calendar?cid=czNkcmltNzRnbG05dWtsY2E4ZjlqNnZhaGdAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

┆Issue is synchronized with this [Trello card](https://trello.com/c/xMETq4n8)

**Comment by lourdesvera** [comment]
We have the google calendar too: https://calendar.google.com/calendar?cid=czNkcmltNzRnbG05dWtsY2E4ZjlqNnZhaGdAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

**Comment by ericnost** [comment]
@lourdesvera Oh right! I'm sorry I forgot about that. I've changed this issue to be more about adding your availability.

**Comment by Frijol** [comment]
What should this look like– hours when you're working, or more like time you're taking off? (would lean toward the latter)

**Comment by ericnost** [comment]
Oh, good question @Frijol. Yea, I was thinking time you're taking off.

**Comment by Frijol** [comment]
✅ done!

(process suggestion: for multi-person tasks like these, shall we comment when done & unassign ourselves?)

**Comment by crgreenleaf** [comment]
Done!

**Comment by shansen5** [comment]
No current plans to be unavailable.

**Comment by lourdesvera** [comment]
@saraannwylie can you add any weeks off?

**Comment by lourdesvera** [comment]
@maalvikabhat @lesliealanis @mraisle this is a good first issue! Can you comment when you're done?

**Comment by mraisle** [comment]
@lourdesvera I'm still only seeing "busy" appear on the EEW Planning and Personnel Calendar . . .that is, I can't see any specific details, who's busy, etc.? could you invite me to this caendar?

**Comment by maalvikabhat** [comment]
I'm having the same problem as @mraisle  -- is there something I'm missing?

**Comment by lesliealanis** [comment]
Hi @lourdesvera I'm also having the same issues, I can access the calendar and see when people are busy but I can't see who is busy and I can't add my busy days to the calendar.

**Comment by lourdesvera** [comment]
has everyone added? @mraisle @maalvikabhat

**Comment by mraisle** [comment]
hey @lourdesvera still having the issue that I only see "busy" on the calendar . . .seems like I haven't been invited to edit still? Sorry for the delay!

**Comment by mraisle** [comment]
@lourdesvera I still don't seem to have anything other than view access to this EEW personnel calendar.

**Comment by calderEDJ** [comment]
done! does anyone else still have to add their availability or can I close the issue?

**Comment by maalvikabhat** [comment]
completed! i can close the issue up
