### ISSUE TITLE
Design some social support structure for intern program

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#148]
Not something we've talked about a lot, but it would be really nice to give the interns some explicit social programming (minimum version would be regular happy hour type calls). Thoughts?

┆Issue is synchronized with this [Trello card](https://trello.com/c/r2d3JIoB)

**Comment by lourdesvera** [comment]
How about happy hour every other thursday afternoon after EDJ?

**Comment by Frijol** [comment]
cc @calderEDJ @crgreenleaf

**Comment by Frijol** [comment]
cc @gabrielletrudo

**Comment by crgreenleaf** [comment]
@calderEDJ  and I can work on this Monday.

**Comment by Frijol** [comment]
Added Thursday Socials per https://github.com/edgi-govdata-archiving/EEW_Planning/issues/166!

**Comment by lourdesvera** [comment]
Since we added the socials, let's close this issue?

**Comment by Frijol** [comment]
Was thinking it might be important for there to be some intern-only space too. @crgreenleaf what do you think?

**Comment by crgreenleaf** [comment]
I'd love to schedule a bi-weekly intern hang or something. @calderEDJ @maalvikabhat @lesliealanis @gabrielletrudo @mraisle what do you all think? Feel free to just thumbs up react if this sounds ok?
