### ISSUE TITLE
Data Science Track Primer Template

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#15]
[Data Science Track Primer](https://drive.google.com/open?id=1U5dXweG-YBBzz1FYpOJzLvh6YZWJLivTb7BuaIIFe_o)

┆Issue is synchronized with this [Trello card](https://trello.com/c/naGqTvCy)

**Comment by lourdesvera** [comment]
Hey @maalvikabhat @ericnost just tagging you in this. Do you think this is a to-do for this week or next to finish it? I think it should just be a place to link to the notebooks, EEW tracker, etc. and give it all context.

**Comment by ericnost** [comment]
@lourdesvera I think this is feasible to complete by the end of next week.

**Comment by ericnost** [comment]
Held up. I think we are in a good spot with this, but it's unclear whether / how this could be a general primer vs one for a specific partnership/event.
