### ISSUE TITLE
Use Seaborn for better graphs?

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#153]
Seaborn is a graphing library built on top of matplotlib (what we currently use). It promises color palettes including for folks w visual disabilities and for prints + easier customization. The con is that we'd have to install the library in each of our environments (and we're not using e.g. conda for package management.. maybe another conversation)

https://seaborn.pydata.org/installing.html

Does anyone have experience with it? cc @lourdesvera @shansen5 @ericnost

┆Issue is synchronized with this [Trello card](https://trello.com/c/Vb5WQihf)

**Comment by ericnost** [comment]
I've heard of, but never used it. I think I've seen it used in R actually.

I don't mind installing it locally. I was able to import the library into Colab without issue.

**Comment by Frijol** [comment]
cc @lourdesvera

**Comment by ericnost** [comment]
ggplot, a popular library for visualization in R, is now available in Python: http://ggplot.yhathq.com/

**Comment by maalvikabhat** [comment]
I've used and love seaborn if we want to make the sunrise notebook graphs a different color, etc

**Comment by ericnost** [comment]
@maalvikabhat Oh, awesome! That would be fantastic - I'll create an issue in the Sunrise repo.

**Comment by Frijol** [comment]
@maalvikabhat yay I'm excited to see what that looks like! Do you think we should adopt seaborn across the notebooks generally?

**Comment by maalvikabhat** [comment]
I think that would be a good idea! From a communications perspective, we can make the color palettes match the EDGI brand for social media/the website, etc. 
seaborn also generally allows for more interesting and dynamic visualizations! I could help with adopting it across notebooks if we deem that important :)

**Comment by Frijol** [comment]
Cool! Here are the EDGI brand guidelines in case you need them: https://drive.google.com/file/d/0B9ycoIVdlgMFeFRIM0Z3WEZaNVU/view?usp=sharing

**Comment by lourdesvera** [comment]
@Frijol are we closing this?

**Comment by Frijol** [comment]
Sure, I think so!
