### ISSUE TITLE
Data & Activism Event at U Illinois Chicago

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#154]
We were invited to speak at https://uicsise.com/ July 15th, please see https://app.slack.com/client/T32U2HQG1/CKN6FMX42/thread/CKN6FMX42-1591121693.375100

cc @ericnost @csellers9

┆Issue is synchronized with this [Trello card](https://trello.com/c/XtkYD6up)

**Comment by lourdesvera** [comment]
+1

**Comment by Frijol** [comment]
Updating, we discussed in All-EEW meeting today & @ericnost is taking point

**Comment by ericnost** [comment]
Maybe missed the boat?

**Comment by ericnost** [comment]
Or not! I have responded to the organizers, and I think we will be signed up. Closing this issue for now. Will re-open for a discussion of how to prepare.
