### ISSUE TITLE
Create detailed EEW presentation template powerpoint

### ISSUE THREAD

**Issue by crgreenleaf** [edgi-govdata-archiving/EEW_Planning#157]
Well designed template and speakers notes to use internally and in the future pass to organization partners.

┆Issue is synchronized with this [Trello card](https://trello.com/c/wFFWxSIE)

**Comment by lourdesvera** [comment]
When should we have this done by?

**Comment by lourdesvera** [comment]
@crgreenleaf how is this going?

**Comment by crgreenleaf** [comment]
I have the graphic design outline pretty much done - is there anything we need it for coming up?
https://www.canva.com/design/DAD-967HmM0/share/preview?token=n0i2UeZRJuUvVe8mdfPuLA&role=EDITOR&utm_content=DAD-967HmM0&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by lesliealanis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue 157](https://trello.com/c/tXsmBWDD/55-issue-157)

**Comment by lourdesvera** [comment]
@crgreenleaf @lesliealanis can we turn this into a powerpoint and then review it? It'd be good to close this issue and have the powerpoint on hand for whenever we need it

**Comment by saraannwylie** [comment]
I can review this if needed?

**Comment by lesliealanis** [comment]
I downloaded the canva version made a google PowerPoint version: https://docs.google.com/presentation/d/1F4BLhCnl229D2VFGKyuvgY7Rv1zDrdmM39vsY5oK9o0/edit?usp=sharing
