### ISSUE TITLE
List the EEW Slack channels

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#159]
Would the readme of this repo make sense as a place to list these?

| Channel | Description |
|-|-|
| #data_wg | EDGI's general channel for data and archiving topics, including EEW notebook development and decentralized web work |
| #echo_projects |  The general channel for all projects related to ECHO, including EEW, ECHO classes, ECHO UX research, and others. |
| #eew_coordination | The general channel for everything related to EEW and EEW planning. This will be the main channel that you will be communicating in |
| #eew_daily_scrum | A bot posts every day to ask check-in questions so the EEW team can share what they are working on |
| #eew_issues | A bot posts updates to Github issues in the EEW_Planning and Environmental_Enforcement_Watch repos |
| #envirodatajustice | This is the channel about the broader theory behind environmental data justice and resources about environmental justice and data justice activism |
| #stupid_questions | For asking questions, especially questions you feel like maybe you should know the answer to already |

┆Issue is synchronized with this [Trello card](https://trello.com/c/KPILqtm8)

**Comment by Frijol** [comment]
@lourdesvera would you be able to add descriptions to the couple of slack channels above I'm less sure about?

**Comment by lourdesvera** [comment]
great idea
