### ISSUE TITLE
Data Visualization Track Primer

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#16]
[Data Visualization Track Primer](https://drive.google.com/open?id=17wTMofkoImPMowXaUwodEALDny3VA5YJsE1hp72ERuM)

┆Issue is synchronized with this [Trello card](https://trello.com/c/WXuDPzFp)

**Comment by ericnost** [comment]
progress made today!

Still to do:
- Add more categories of outputs
- Add more resources
- Accept changes to the doc
