### ISSUE TITLE
Complete edits to Start Here Primer

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#161]
There still are some lingering edits to be done at the Start Here Primer. https://docs.google.com/document/d/12q28CfslRCow5YxC5DHkWx3S4hemefd5TDsECz2GC3o/edit#heading=h.fccfnstpxt1

┆Issue is synchronized with this [Trello card](https://trello.com/c/sCXVXKYu)

**Comment by lourdesvera** [comment]
@lesliealanis will take a pass through, @lourdesvera will review, and close the issue

**Comment by lourdesvera** [comment]
➤ lourdesvera commented:

lesliealanis will take a pass through, lourdesvera will review, and close the issue

**Comment by lourdesvera** [comment]
➤ lourdesvera commented:

lesliealanis will take a pass through, lourdesvera will review, and close the issue

**Comment by lesliealanis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [edits to welcome to eew](https://trello.com/c/jDm3h6y2/54-edits-to-welcome-to-eew)

**Comment by lesliealanis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Complete edits to Start Here Primer #161](https://trello.com/c/O6XKfvgu/43-complete-edits-to-start-here-primer-161)

**Comment by lesliealanis** [comment]
Hi @lourdesvera , I think this is ready for review
