### ISSUE TITLE
Apply to speak at PyCon AU?

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#165]
https://2020.pycon.org.au/

4-6 September, virtual
CFP expected to open within the week

┆Issue is synchronized with this [Trello card](https://trello.com/c/PdxviiHp)

**Comment by Frijol** [comment]
[Call for Proposals](https://2020.pycon.org.au/speak/) is open until July 12th! This is a well-respected international conference on Python, including related topics on community & open source. New speakers are explicitly welcome to apply.

I think this would be an excellent fit to showcase our EEW work, and a really good way for the presenter to get their name out into the professional developer community (was really good for my career to do similar in the Node/JS communities).

Is this exciting to anyone? @maalvikabhat @ericnost @shansen5

Typically for a CFP you need to have a good idea for a talk ("How we use Jupyter Notebooks to engage the public with pollution data"?) that you can summarize with a title and paragraph of text. You don't need the full presentation until the actual event.

**Comment by maalvikabhat** [comment]
I'm interested! I think something along the lines of making environmental justice analysis readily available/accessible with Jupyter Notebooks is fascinating. I could help write the proposal, create the presentation, or anything else we would need! Let me know

**Comment by Frijol** [comment]
I'm happy to be a resource at any point along this process

**Comment by maalvikabhat** [comment]
thank you so much, Kelsey!

**Comment by ericnost** [comment]
I am looking for one more reviewer on a proposal @maalvikabhat has put together to present about the notebooks at PyCon Australia: https://docs.google.com/document/d/1WFSssLN-7pAjeezKDLt1vu3TdlwXRM0-8v-GusEKTdI/edit (we'd also submit this or something similar to JupyterCon) Kelsey and I have weighed in already but, as in academic peer review, it would be good to get a third perspective! @saraannwylie @lourdesvera?

**Comment by Frijol** [comment]
@maalvikabhat this got submitted, right?

**Comment by maalvikabhat** [comment]
Yes :) So has the JupyterCon proposal
