### ISSUE TITLE
EEW Intern Onboarding Project Board

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#168]
Create a project board for EEW interns to work through as they onboard. Use this [onboarding document](https://docs.google.com/document/d/1ZAdmFXdK4K4VA4s7bkuPPksDJBedlGr4tDrMTZ8xch0/edit#) as a guide for their activities.

[Project board here](https://github.com/edgi-govdata-archiving/EEW_Planning/projects/8)

┆Issue is synchronized with this [Trello card](https://trello.com/c/8O8cknsg)

**Comment by lourdesvera** [comment]
@Frijol can I assign you to this? This is the major task for today and I think would take about 1.5-2 hours.

**Comment by Frijol** [comment]
Yep! Drafted a template here: https://github.com/edgi-govdata-archiving/EEW_Planning/projects/8

I think it's pretty thorough but please take a look and make sure! Once you give thumbs up, I can copy this board over so each new intern has their own board to work through.

**Comment by ericnost** [comment]
@Frijol I made some edits to the notebook exercise, to steer interns towards the notebooks to which we are directing our energy now (Cross-Program, GHGRP, COVID).

**Comment by lourdesvera** [comment]
Thank you @Frijol and @ericnost ! Should we convert these notes to issues? there are some where I want to add smaller to-dos and more links

**Comment by Frijol** [comment]
I'd rather not convert the notes to issues in this circumstance if we can avoid it; it will help keep the onboarding tasks for the individual interns from getting confused with each other & with the main issues list. But I think it's ok to make long notes

**Comment by lourdesvera** [comment]
@saraannwylie do you want to review this?

**Comment by saraannwylie** [comment]
This looks good to me! Two questions for @lourdesvera and @Frijol will we make a copy of this for each intern? What should I link to in the onboarding doc here: https://docs.google.com/document/d/1ZAdmFXdK4K4VA4s7bkuPPksDJBedlGr4tDrMTZ8xch0/edit#

**Comment by saraannwylie** [comment]
So I could email the interns tonight I just changed the doc to say they'd receive this on monday @lourdesvera @Frijol

**Comment by Frijol** [comment]
All set! Here are boards for:

* [Megan](https://github.com/orgs/edgi-govdata-archiving/projects/6)
* [Maalvika](https://github.com/orgs/edgi-govdata-archiving/projects/7)
* [Leslie](https://github.com/orgs/edgi-govdata-archiving/projects/8)
* [Gabby](https://github.com/orgs/edgi-govdata-archiving/projects/9)
