### ISSUE TITLE
Questions and Stories Track Primer

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#17]
[Questions and Stories Track](https://drive.google.com/open?id=1mnoOV7DGq5DBCxTaf3h8MMG8lGhOCFXkmoeVK-2ZkSU)

┆Issue is synchronized with this [Trello card](https://trello.com/c/HJqRiR7m)

**Comment by lesliealanis** [comment]
Hi @Frijol I keep getting an error with the Trello card, I'm not sure if it's shared to my lesliealaniscazares@gmail.com

**Comment by Frijol** [comment]
@lourdesvera can you take a look at the Trello sync? ^ (I'm not really up on that)

**Comment by lourdesvera** [comment]
@lesliealanis sent you the invite if you want to work from the trello. I haven't been up with it, but it's all yours if you'd like
