### ISSUE TITLE
Intro to EEW Powerpoint for All-EDGI meeting 6/12/20

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#170]
Create a 15 minute intro to EEW presentation for All-EDGI meeting on Friday the 12th. Connect to #157

┆Issue is synchronized with this [Trello card](https://trello.com/c/HmH8tHSk)

**Comment by saraannwylie** [comment]
https://docs.google.com/presentation/d/1uxVjNeksFbKBkFr8cveyKA606EksfvBQL86Ur1bXZtI/edit#slide=id.g86f2c85277_1_55, here's the presentation
