### ISSUE TITLE
Develop notebook-based "homework" for interns

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/EEW_Planning#172]
We had discussed the idea of asking the interns to try to answer some questions with the notebooks. Though they've already test-run at least 1 nb, and will get a walk-through this week, it might be helpful to ask them to do more targeted exercises to see what can/can't be done with the scripts. *What do you think?*

Draft (edited based on comments): 

Data science
- Looking deeper into the data. What is there that we haven't exposed yet? How can we see and then explain the data that is missing?
- What other data sources can be brought in to better show the context of the ECHO data? E.g. census demographics. (ECHO_EXPORTER has FAC_DERIVED_CB2010 - census blocks.)

Data visualization
- Making more compelling visualizations of the data we already know is being imported into the notebooks.

Research and contextualization
- Q

Storytelling
 - Q

┆Issue is synchronized with this [Trello card](https://trello.com/c/T7O8KYZw)

**Comment by shansen5** [comment]
1.  Making more compelling visualizations of the data we already know is being imported into the notebooks.
2.  Looking deeper into the data.  What is there that we haven't exposed yet?  How can we see and then explain the data that is missing?
3.  What other data sources can be brought in to better show the context of the ECHO data?  E.g. census demographics.  (ECHO_EXPORTER has FAC_DERIVED_CB2010 - census blocks.)

**Comment by Frijol** [comment]
@ericnost did this already happen?

**Comment by ericnost** [comment]
It happened enough! With the COVID nb event we did last week. Closing.
