### ISSUE TITLE
Research & context questions (collector issue)

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#173]
This issue is a temporary collector of questions we want to answer through research & contextualization. Please add!

* a list of all the chemicals that are monitored in ECHO and what is known about them re human and ecological health
* What is a “hydrocarbon basin”?
* What does “25,000 metric tons CO2e or more per year” actually amount to?
* Same question for 460,000 Mscf or more of natural gas per year
* How long does it typically take for supply chain data to take effect?

┆Issue is synchronized with this [Trello card](https://trello.com/c/FjK5oJtF)

**Comment by mraisle** [comment]
related to the Issue #121

**Comment by mraisle** [comment]
Seeking clarification from @Frijol, @crgreenleaf and/or @lourdesvera  . . . is this different than issue #18 , the Research and Contextualization Primer? By that I mean would the answers to these questions by put into the primer?

**Comment by Frijol** [comment]
Good question! Yes, this is different – the primer is about *how* to do the research & contextualization track, this issue is a place we're putting specific questions that would be helpful for the track to answer.

You're probably the right person to ask @mraisle – what would be a better way to surface & keep track of questions that come up such that the research & context track might answer them?

**Comment by Frijol** [comment]
Should this now all go into the EEW Tracker?

**Comment by mraisle** [comment]
Should we close this issue? if not, what needs to happen next here?

**Comment by lourdesvera** [comment]
@mraisle Let's close this issue. We can drop questions into the [EEW Tracker ](https://docs.google.com/spreadsheets/d/1Z2rBoGqb_SXW6oAu12A6TCWEJGV1pk0YxL13P_Z5Wlw/edit?usp=drive_web&ouid=110602273190303993217)
