### ISSUE TITLE
Make a poster or video for ESIP summer meeting

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#174]
Follow-on work from https://github.com/edgi-govdata-archiving/EEW_Planning/issues/136

┆Issue is synchronized with this [Trello card](https://trello.com/c/FiYkWDKu)

**Comment by Frijol** [comment]
is this planned to be the same video as https://github.com/edgi-govdata-archiving/EEW_Planning/issues/194?

**Comment by crgreenleaf** [comment]
@Frijol It's an offshoot!
