### ISSUE TITLE
Script to convert toxic compounds from ug/m3 to ppb

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#176]
* [x] Create spreadsheet of pollutants and their molecular weights.
* [x] create script or function based on this equation https://www2.dmu.dk/AtmosphericEnvironment/Expost/database/docs/PPM_conversion.pdf
* [x] create input for temperature.

┆Issue is synchronized with this [Trello card](https://trello.com/c/tiqtnHUe)

**Comment by ericnost** [comment]
The Combined Air Emissions table we have is structured as follows, for each facility, for each year, for each pollutant, pounds emitted. So, I'm wondering if we need to do conversions? The full Discharge Monitoring Reports for Water are a bit more detailed and sometimes measured in ug/m3. But there are real obstacles in accessing the full DMRs.

**Comment by lourdesvera** [comment]
@mraisle @ericnost @maalvikabhat 
I created a Jupyter Notebook in R to convert measurements between ppb and ug/m3 and to compare them to thresholds. This might be good for some ECHO data to determine which thresholds measurements are exceeding (i.e. they might exceed certain state thresholds but not EPA). 

https://colab.research.google.com/drive/1kVVqe_Xmm-oTnXDxw67-7d5eHGX9Udr7?usp=sharing

It needs to be cleaned up and put into a repo, so that'll be the next issue.
