### ISSUE TITLE
Tailor primers for Sunrise event

### ISSUE THREAD

**Issue by crgreenleaf** [edgi-govdata-archiving/EEW_Planning#178]
┆Issue is synchronized with this [Trello card](https://trello.com/c/510LSKMh)

**Comment by saraannwylie** [comment]
@lesliealanis think this is something you can work on with @crgreenleaf

**Comment by ericnost** [comment]
We have so many primers! I am worried about the time this will take. 

In addition, we have so many moving pieces. The Sunrise notebook isn't even drafted, so it may be hard to tailor some primers? That said, I think tailoring like the research primer towards the targets we have discussed can be started and would be super helpful.

**Comment by ericnost** [comment]
to do [potentially incomplete list]
- [ ] Create Sunrise-specific version of Data Science primer https://docs.google.com/document/d/1U5dXweG-YBBzz1FYpOJzLvh6YZWJLivTb7BuaIIFe_o/edit
- [ ] Create Sunrise-specific version of Congressional District primer https://docs.google.com/document/d/17fBEiAVdTJvPmO7ZRC86vfGKkfHMVMHkQnyMJOHqMjw/edit
- [ ] Add examples/example workflow to Data Viz primer https://docs.google.com/document/d/17wTMofkoImPMowXaUwodEALDny3VA5YJsE1hp72ERuM/edit

**Comment by lourdesvera** [comment]
Go team
