### ISSUE TITLE
Make Storytelling deck for track

### ISSUE THREAD

**Issue by crgreenleaf** [edgi-govdata-archiving/EEW_Planning#186]
┆Issue is synchronized with this [Trello card](https://trello.com/c/7ljqOQe4)

**Comment by crgreenleaf** [comment]
https://docs.google.com/presentation/d/1h-xdL1BVM90yxvPplCumFcfZsqbOWbCAbCgSOAd2KpY/edit#slide=id.g8a6a8961be_0_63

**Comment by lourdesvera** [comment]
let's tag reviewers @crgreenleaf

**Comment by saraannwylie** [comment]
Is this different from the Mural? @lesliealanis could you link the mural in here if it's not?

**Comment by lesliealanis** [comment]
@saraannwylie here it is: https://app.mural.co/invitation/mural/managementworkshops7524/1593052252947?sender=lesliealaniscazares6748&key=46482aea-ec4c-4f34-8099-b15517292a65

**Comment by lourdesvera** [comment]
@lesliealanis @saraannwylie @crgreenleaf we did want to make the mural an optional breakout room, so it'll be good to have the intro and conclusion slides to guide the track as a whole

**Comment by lesliealanis** [comment]
@lourdesvera I changed it a little to include the same questions from the mural but in a more conversational format but i saved a copy of the original that @crgreenleaf made
