### ISSUE TITLE
Practice integrating Slack and Github

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/EEW_Planning#189]
Make a comment on slack, and use the integration tool to copy it here.

┆Issue is synchronized with this [Trello card](https://trello.com/c/kuYaj3fF)

**Comment by ericnost** [comment]
> Advanced tip: if you hover over a message and click the three dots ... you should see a menu item that says something like comment or PR on Github. After you connect to your GH account, you can turn the slack message into a GH issue. This is a little buggy. I find that you have to manually copy/paste the repo link you want the issue to appear in.
<sub>[View in Slack](https://edgi.slack.com/archives/C014PBR66BH/p1592407288017500)</sub>

**Comment by ericnost** [comment]
> ^^^ Correction to above: you have to go to GH and first create the issue (or find an issue you want to add to). Then copy that link and paste it into the menu that appears when you click on the slack message...The slack message will then be copied to the issue on GH
<sub>[View in Slack](https://edgi.slack.com/archives/C014PBR66BH/p1592407511017700)</sub>

**Comment by Frijol** [comment]
I'm getting an oauth error trying to finish my GH/Slack integration :( `Error: OAuth State mismatch, please try again.`

**Comment by ericnost** [comment]
> testing github integration
<sub>[View in Slack](https://edgi.slack.com/archives/C015DK0LKPS/p1593136420031600)</sub>

**Comment by ericnost** [comment]
Hmm! I'm not sure what that would mean.

> I'm getting an oauth error trying to finish my GH/Slack integration :( `Error: OAuth State mismatch, please try again.`
