### ISSUE TITLE
Practice sharing issues with lots of people assigned to them

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#193]
Sometimes we'll have an issue where *everybody* needs to do something. We've decided that a good workflow when this is the case is to make the issue and assign everybody who needs to do it.

Assignees should:
1. Read the issue and take any actions required
2. When complete, comment indicating that you've finished and unassign yourself
3. If you are last, close the issue

Try it out with this issue! I'll assign to several people, you can mark complete when you've read this.

(I know this is review for some of you, but I wasn't sure who!)

┆Issue is synchronized with this [Trello card](https://trello.com/c/4sir2Cgk)

**Comment by ericnost** [comment]
Completed

**Comment by crgreenleaf** [comment]
Completed

**Comment by mraisle** [comment]
Completed

**Comment by lesliealanis** [comment]
Completed

**Comment by calderEDJ** [comment]
Completed

**Comment by maalvikabhat** [comment]
Complete

**Comment by gabrielletrudo** [comment]
Completed

**Comment by lourdesvera** [comment]
completed

**Comment by lourdesvera** [comment]
@saraannwylie I think you are the remaining assignee!

**Comment by Frijol** [comment]
Don't forget to unassign yourself after completing! But I think this is good enough, closing the issue
