### ISSUE TITLE
EEW Promo Video

### ISSUE THREAD

**Issue by crgreenleaf** [edgi-govdata-archiving/EEW_Planning#194]
Create promo video with a short notebook demo (zoom recorded with explanation from one of us) and use the [EEW outreach deck](https://drive.google.com/file/d/1nlHFaosaeugCvHTXI29HW0XLShFHtazO/view?usp=sharing) to create visualization of event structure

┆Issue is synchronized with this [Trello card](https://trello.com/c/EpqsXA7R)

**Comment by crgreenleaf** [comment]
View draft of video here: https://www.canva.com/design/DAD_5lPdzSc/3aX186A3-L2kDS5AP3AnZQ/view?utm_content=DAD_5lPdzSc&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by mraisle** [comment]
Casey, the video is awesome! yay canva! Here are my comments: 
- [] 0:51 where it says "EDGI members have come together and developed . . ." feels wordy to me. Room for more improvement, but here's a start at shortening: "EDGI members have developed a structure to teach anyone how to monitor their environmental data" - by saying plural "members" its clear it was done together and by saying "anyone" and in combo with content later in the video its already clear that it's public. 
- [] right at 2 minutes the text that starts "see how many facilities" as well as the text immediately after that says "find out what facilities" are both on screen too short of a time to ready. 
- [] speaking to above point, it might take up less time in some parts if someone speaks and there are subtitles? esp. in the notebook overview portion. 
- [] on shortening the video: section starting at minute 1 about the goals of the event communicate the same info as the run through of the event track chart starting at 2:57. My suggestion would be to cut the part between 2:57-3:20 and then move the line that start with "together, we can . . ." to the clip around 2:53.

**Comment by Frijol** [comment]
This is super cool! Would we have someone read it aloud for the final video?
It also might be helpful to put highlighting behind the words on many (all?) of the slides just to help them stand out better (see https://www.instagram.com/p/B79BStzDqqe/ for example). I had a hard time reading some of them.

**Comment by Frijol** [comment]
and back with something from the Free Music Archive, like maybe "Beyond Dreams" from this search: https://www.freemusicarchive.org/search?adv=1&quicksearch=inspiring&&
