### ISSUE TITLE
Switch database meeting link?

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/EEW_Planning#195]
@lourdesvera  - It looks like I'll be coordinating the Tuesday 1pm database meetings. I think we might as well go ahead and switch to using the same link as the 2pm sprint meetings, and ask the sprint team to jump on at 1:45/1:50 so we can overlap. That's the idea right?

The problem is that while I can change the info on the google calendar, I don't know how to update the Slackbot / if I have access to it. Is there a writeup somewhere on how to do this? 

cc: @Frijol

┆Issue is synchronized with this [Trello card](https://trello.com/c/eVYEEpf7)

**Comment by lourdesvera** [comment]
@ericnost sorry I was silent on this. It's done! I'm closing the issue.

**Comment by Frijol** [comment]
@ericnost were you able to update the slackbot reminders?

**Comment by ericnost** [comment]
@Frijol No, I couldn't for the life of me figure out. Slackbot wouldn't understand me when I tried to create a new reminder.

**Comment by Frijol** [comment]
oh damn, I can take a look

**Comment by lourdesvera** [comment]
@Frijol do you want me to do it?

**Comment by Frijol** [comment]
sure!

**Comment by Frijol** [comment]
Done! @ericnost here's the text I used:

```
/remind #eew_coordination “Reminder: ECHO Database meeting in 30 minutes!

Zoom link: https://edgi-video-call-landing-page.herokuapp.com/https://zoom.us/j/85087739115
Notes doc: https://docs.google.com/document/d/1ZraEefQMhF1XWDrZi8Igr9gQUWD2n2LM5n26CLmxbB8/edit#heading=h.f380hh8prm3n” at 9:30AM every Tuesday
```

**Comment by ericnost** [comment]
Ah thanks @Frijol - the tooltip that recommends how to write a remind command includes square brackets around each part that I took literally.

>Sorry, I didn’t quite get that. I’m easily confused. Perhaps try the words in a different order, or use quotes around the message you'd like to send. This usually works: `/remind [@someone or #channel] "[what]" [when].`

**Comment by ericnost** [comment]
I tried entering the exact same info as you did @Frijol and @Slackbot says "I’m sorry! I can’t find that channel." I give up.

**Comment by Frijol** [comment]
oh yeah for some reason you have to backspace the end of it and let it autocomplete (?)
