### ISSUE TITLE
Develop a QA process for notebooks

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#197]
Draft a process that should take place before each event for every notebook, ensuring that notebooks work, are clear to use, and are not misleading

┆Issue is synchronized with this [Trello card](https://trello.com/c/crMgri8n)

**Comment by Frijol** [comment]
cc @ericnost @maalvikabhat @shansen5

**Comment by ericnost** [comment]
Same as #203

**Comment by Frijol** [comment]
Beginning to outline what needs to be tested:

## Checklist

### Basic function
* Does it run all the way through as a Colab notebook when you are signed in as someone with no special EDGI access?
* Does it create the outputs it is supposed to create (graphs, data exports, ?)?

### Usability
* Are the instructions sensible to a non-coder?

### Completeness & accuracy
* Do all code blocks do what comments and text say it will do?
* Is the data used appropriate to the questions being asked?

### Contextualization
* Are there any abbreviations or technical references that would leave a non-expert confused?

### Impartiality
* Does the language used make sense across all of the parameters the notebook might use (different districts, months, etc. depending on notebook)?
* Is the language impartial (not opinionated)?
* Are all context references factual and cited?

### Figure completeness
* Does every figure have a title, legend, and labels on x and y axes?

### Figure accuracy
* Are all labels, titles, and legend items accurate to what is being displayed?
* If this notebook is run across widely varied parameters, can the figures from different runs be directly compared without being misleading? (Look out for e.g. auto-scaling, inadequate labeling)

### Figure elegance
* Are figures and figure elements appropriately sized for legibility?
* Do figures compellingly display the answer to a question the notebook asks?

### EDGI and EEW branding
* @gabrielletrudo is there any templating/guidelines we should add here?
* Is the EEW logo included at the top of the notebook?
* Do figures use EDGI brand colors where appropriate?

**Comment by Frijol** [comment]
@maalvikabhat would you be a good person to take a first look at the above checklist? Anything that would be confusing to a reviewer, anything else we should be checking for?

**Comment by maalvikabhat** [comment]
I can definitely do this!

Was wondering if we wanted more comments? Or something to explain what cells/functions are doing as to not intimidate non-coders?

**Comment by Frijol** [comment]
> Was wondering if we wanted more comments? Or something to explain what cells/functions are doing as to not intimidate non-coders?

In general yes! @lourdesvera did some of this a while ago and it's very helpful – also opens it up for more people to check through the notebooks when we're doing validation.

Do you have a good metric in mind we might add to this list for commenting, or do we want it more as a general principle while we work on them?

**Comment by maalvikabhat** [comment]
Just a general principle, probably.  Also, some text contextualizing the data could be helpful. (Where we're getting the data from, how it's calculated, over what time periods, etc)

**Comment by saraannwylie** [comment]
> Just a general principle, probably. Also, some text contextualizing the data could be helpful. (Where we're getting the data from, how it's calculated, over what time periods, etc) good point @maalvikabhat, @mraisle could you help with that for the Sunrise notebook?

**Comment by saraannwylie** [comment]
We should spot check specific facility reports against the online ECHO data?

**Comment by saraannwylie** [comment]
Is there or should we add something assuring the provenance of the data in the stonybrook database from ECHO--like some kind of metadata tag saying the time/date of the download to stonybrook?

**Comment by mraisle** [comment]
@saraannwylie Yep I can help with that in the next draft. 
Also, @maalvikabhat @Frijol, added a few things to your original list and tried to incorporate the comments here. here's what I've got: 


## Checklist

### Basic function
* Does it run all the way through as a Colab notebook when you are signed in as someone with no special EDGI access?
* Does it create the outputs it is supposed to create (graphs, data exports, ?)?
* Does is run smoothly when 10+ people are on at the same time?

### Usability
* Are the instructions sensible to a non-coder?
* Have code blocks been streamlined as much as possible (combined where they could be)?

### Completeness & accuracy
* Do all code blocks do what comments and text say it will do?
* Is the data used appropriate to the questions being asked?
* Have we spot checked 3 specific facility reports against the online ECHO data?

### Contextualization
* Are there any abbreviations or technical references that would leave a non-expert confused?
* Is it clear where the data is coming from, what the timeline is, where the data may be lacking?

### Impartiality
* Does the language used make sense across all of the parameters the notebook might use (different districts, months, etc. depending on notebook)?
* Is the language impartial (not opinionated)?
* Are all context references factual and cited?

### Figure completeness
* Does every figure have a title, legend, and labels on x and y axes?

### Figure accuracy
* Are all labels, titles, and legend items accurate to what is being displayed?
* If this notebook is run across widely varied parameters, can the figures from different runs be directly compared without being misleading? (Look out for e.g. auto-scaling, inadequate labeling)

### Figure elegance
* Are figures and figure elements appropriately sized for legibility?
* Are scales interpretable?
* Do figures compellingly display the answer to a question the notebook asks?

### EDGI and EEW branding
* @gabrielletrudo is there any templating/guidelines we should add here?
* Is the EEW logo included at the top of the notebook?
* Do figures use EDGI brand colors where appropriate?

**Comment by ericnost** [comment]
I am closing this and adding this set of questions to the Cross-Program (and eventually, Sunrise) notebooks repos.
