### ISSUE TITLE
IRB for Exit Survey

### ISSUE THREAD

**Issue by mraisle** [edgi-govdata-archiving/EEW_Planning#198]
┆Issue is synchronized with this [Trello card](https://trello.com/c/WSg5Y3NQ)

**Comment by mraisle** [comment]
@saraannwylie and @ericnost would you like to be assigned to this?

**Comment by ericnost** [comment]
In the 🦥  spirit, one thing we did for this related paper (where we hosted a design challenge event around EPA hazardous waste data) was to conduct follow-up interviews with participants ~ 1 year _after_ the event. There are obviously methodological issues there, and the EEW events do not have quite the same goal, but I could see it working in one way or another and being a valuable contribution. It would give us more time to reflect, prepare, do the IRB, etc.  https://uwcart.github.io/waste/data/Geoforum_final.pdf

**Comment by lourdesvera** [comment]
@ericnost Can I assign you to this? What do we think the next steps are?

**Comment by ericnost** [comment]
My feeling is that I don't think we can move forward on this until we have a meeting dedicated solely to discussing the academic orientation of EEW: What do we want to get out of this? What capacity do we have? I don't think we would be able to pull off an IRB in the short-term given everything else we have to do to set up events.

**Comment by saraannwylie** [comment]
I agree, I think we should draft an exit survey to figure out what we need for EEW/EDGI, I don't think we should think about this is a research project per say, we didn't for data rescue and wrote a lot about it.
