### ISSUE TITLE
MySQL_Cheat_Sheet

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#20]
[Cheat Sheet for MySQL with popular commands](https://drive.google.com/open?id=1eH6QRstWOp0wdnbyag93jPvXLp1enbxuvWKxPzzEf5E)

┆Issue is synchronized with this [Trello card](https://trello.com/c/PCSciBut)

**Comment by shansen5** [comment]
Full tutorial:  https://www.mysqltutorial.org/
Tutorial for creating database queries with SQL:  https://www.sqltutorial.org/
