### ISSUE TITLE
Review Visuals for accuracy and ~elegance

### ISSUE THREAD

**Issue by mraisle** [edgi-govdata-archiving/EEW_Planning#202]
┆Issue is synchronized with this [Trello card](https://trello.com/c/0pK0cmWr)

**Comment by ericnost** [comment]
I think the focus here is on the notebook visuals, including charts and maps.

See also #153

**Comment by Frijol** [comment]
Should this be: develop process to review notebook visuals? If so, I think this is a part of #197 
We also need a process to review visuals in final reports

**Comment by lourdesvera** [comment]
Closing and combining with #197
