### ISSUE TITLE
Content for promotion and sharing of EEW

### ISSUE THREAD

**Issue by mraisle** [edgi-govdata-archiving/EEW_Planning#205]
* [x] powerpoint template about EEW
* [x] promo video
* [x] drafted tweets
* [x] drafted facebook posts
* [x] e-mail templates

┆Issue is synchronized with this [Trello card](https://trello.com/c/tN5Swyyg)

**Comment by mraisle** [comment]
@crgreenleaf @gabrielletrudo would you like to be assigned to this?

**Comment by lourdesvera** [comment]
linked with #182

**Comment by lesliealanis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/edgi-govdata-archiving/EEW_Planning/issues/205](https://trello.com/c/5nb2EZkP/56-https-githubcom-edgi-govdata-archiving-eewplanning-issues-205)

**Comment by lourdesvera** [comment]
We need to break this issue down into smaller, more concrete steps. @gabrielletrudo @lesliealanis can you help?

**Comment by gabrielletrudo** [comment]
I am drafting some tweets that will help introduce the EEW project (wouldn't be a bad idea to write up an EDGI blog post so we can circulate that, I can talk to Kelly on Thursday in our Comms meeting about this we're going over publishing more generally), and I think once we start posting we should start to build our base (follow, ~50 people a day?) and reach out to Sunrise when we get closer to the event and perhaps collaborate on a messaging strategy (aka just make sure they are promoting the event as well).

**Comment by gabrielletrudo** [comment]
I can go through the Social Media Plan and add more concrete steps with due dates to keep us on track for the Sunrise workshop on the 18th.

**Comment by lesliealanis** [comment]
@lourdesvera @gabrielletrudo  I can help with the tweets,  let me know what I can help with!

**Comment by lesliealanis** [comment]
The tweet drafts are at the bottom of this doc https://docs.google.com/document/d/1MmfSZrexkstz49-eyPzocWIP_6BQflIC_XwnbppqP3k/edit
