### ISSUE TITLE
Everyone clear on their role at event?

### ISSUE THREAD

**Issue by mraisle** [edgi-govdata-archiving/EEW_Planning#208]
Perhaps we all write in our own words what we think our role is at the event as a comment on this message and then unassign ourselves, and then everyone can be reassigned to review once it moves to the "Review" column?

┆Issue is synchronized with this [Trello card](https://trello.com/c/P4Sqo3Op)

**Comment by lesliealanis** [comment]
My roles for the event:
- help write a clear, organized and cohesive storytelling track primer 
- Event structure: 
     - Work with the event agenda and include a storytelling plan or agenda within the event
          - Creating a mural/ PowerPoint or both to use during the storytelling part of the event
- Ask/create questions which encourage storytelling and participation
- Facilitate and encourage storytelling at the event
- Event outreach through social media/other means

**Comment by crgreenleaf** [comment]
- Mainline the outreach to Sunrise Boston (including setting dates, inviting them to planning meetings, making sure their feedback is given on Sunrise notebook)
- Create and make sure they have all materials they need to successfully promote the event internally
- Coordinate Zoom registration 
- Ensure the main primer is ready to go 
- Presenting during event, being on call during event to answer questions, support tracks, and coordinate survey completion at the end of the event

**Comment by Frijol** [comment]
Great idea @mraisle !

My role:
* Support role at event, on hand to facilitate a breakout or present a slide or answer tech questions as called upon
* Event coordinators, feel free to ask me to fill some specific role per event

**Comment by saraannwylie** [comment]
+1 to this being a great idea.

- Not 100% sure what role I would personally play at the Sunrise event, I would be happy to support @mraisle in coordinating the research and contextualization track and @crgreenleaf in preparing for the beginning presentation and wrap up presentation.
- I would be happy to be on call to answer questions or work to document what's happening
- I am cautious that EDGI folks not overwhelm the Sunrisers in terms of numbers, so I suggest we see what the registration is and then gauge how many EDGI folks are actually present.

I am sort of thinking that once this event is truly in motion and happening, I should be focused on organizing the next event with EJ groups.

**Comment by lourdesvera** [comment]
My role at this event would be to:
* facilitate the data visualization track (if there is one?)
* Make sure everyone is tracking their outputs
* Serve as support for people trying to navigate the primers, google drive, notebooks.

**Comment by Frijol** [comment]
Ping on this issue! This one is low-hanging fruit to close by the end of our sprint tomorrow.

**Comment by gabrielletrudo** [comment]
My role at the event would be largely to take notes, pictures (read: screenshots), and craft after-workshop content for social media. I would also be happy to explain the data privacy bit of the Partnership Agreement--that by joining the Zoom they are agreeing to having their picture taken and shared, but they can reach out to me via the EEW email to have their individual photos blurred/obscured.

**Comment by maalvikabhat** [comment]
My role at this event is to:
Serve as tech support for people working with the notebooks & primers

**Comment by ericnost** [comment]
My roles at the event:

- Support for working with notebooks
- Support for explaining environmental law/how EPA programs are structured

**Comment by calderEDJ** [comment]
- Working with Megan and to develop a canva report template for the event and with @crgreenleaf (?) to get feedback from Sunrise folks the template structure/content
- Facilitating the incorporation of findings from research&contextualization tracks into the canva report, maybe helping to facilitate one of these tracks
- Help organize tracking of event data/outputs in google drive during and after the events, coordinate participant off-boarding

**Comment by mraisle** [comment]
- Facilitate the Research and Contextualization track 
- Potentially be on hand to help with any questions around the notebook 
- Be involved in follow-up with Sunrise as they figure out what further research/reporting they'd like to do.
