### ISSUE TITLE
Confirm event date with Sunrise Partners

### ISSUE THREAD

**Issue by mraisle** [edgi-govdata-archiving/EEW_Planning#209]
┆Issue is synchronized with this [Trello card](https://trello.com/c/DHtxQuar)

**Comment by mraisle** [comment]
@crgreenleaf would you like to be assigned to this?

**Comment by ericnost** [comment]
Is this #215?

**Comment by crgreenleaf** [comment]
@ericnost no, this one is confirming event date

**Comment by crgreenleaf** [comment]
Sunrise has proposed Saturday July 18th as the date for this event.
