### ISSUE TITLE
Description of our Database

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#21]
[Description of our Database](https://drive.google.com/open?id=19h3cnLmJShFENDAt4lbYyRM3BQ5h_qBM0C1HCrvM_38)

┆Issue is synchronized with this [Trello card](https://trello.com/c/RZfxaAW1)

**Comment by Frijol** [comment]
Would be very useful to have even basic documentation of the database/how to use. Do we have anything of that type yet? @shansen5 @sunggheel @ericnost @danpascucci

**Comment by ericnost** [comment]
At the very least, we have the sql code that describes the columns in each table. Could start from there. Chris also has some (EDGI) Google Docs describing the priority columns.

**Comment by Frijol** [comment]
related: https://github.com/edgi-govdata-archiving/EEW_Planning/issues/94

**Comment by Frijol** [comment]
I think we've achieved at least a basic version of this via description in the notebooks. We also have the repo of scripts: https://github.com/edgi-govdata-archiving/ECHOEPA-to-SQL which has some description

**Comment by Frijol** [comment]
related: https://github.com/edgi-govdata-archiving/EEW_Planning/issues/94
