### ISSUE TITLE
Start outreach protocol + Meet with NRDC

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#210]
Meeting to start outreach protocol and guidelines for EEW then outline the materials and messaging we want for the NRDC meeting.

* [x] Fill out when2meet for meeting https://www.when2meet.com/?9295068-kusTn
* [x] Hold meeting
* [x] Create 1-2 page outreach guidelines

┆Issue is synchronized with this [Trello card](https://trello.com/c/7lyE5I3C)

**Comment by crgreenleaf** [comment]
Any further movement on this?
