### ISSUE TITLE
Social media plan

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#211]
┆Issue is synchronized with this [Trello card](https://trello.com/c/HiKh6PsV)

**Comment by gabrielletrudo** [comment]
We have a rough social media plan that Kelly put together a few weeks ago in the Google Drive under Media_EEW > Social Media/Outreach Plans_EEW > Social Media Messaging/Strategies. I am happy to discuss with anyone in greater detail. I am going to start drafting tweets this week.

**Comment by lesliealanis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Social media plan #211](https://trello.com/c/Q7KzOcmK/85-social-media-plan-211)

**Comment by lesliealanis** [comment]
@gabrielletrudo I am happy to help with social media, let me know what I can help with! I'll start by looking at the Social Media Messaging/strategies doc

**Comment by gabrielletrudo** [comment]
(More Specific) Social Media plan with deadlines might help us (read: me) stay on track for Sunrise Workshop promo: https://docs.google.com/document/d/1MmfSZrexkstz49-eyPzocWIP_6BQflIC_XwnbppqP3k/edit

**Comment by lourdesvera** [comment]
Let's finish this social media plan and drop it in the EEW planning folder, posting it for review

**Comment by lesliealanis** [comment]
draft tweets at the bottom of https://docs.google.com/document/d/1MmfSZrexkstz49-eyPzocWIP_6BQflIC_XwnbppqP3k/edit

**Comment by gabrielletrudo** [comment]
Updated SM Plan (certain parts still in progress): https://docs.google.com/document/d/1MmfSZrexkstz49-eyPzocWIP_6BQflIC_XwnbppqP3k/edit#
