### ISSUE TITLE
sunrise version of congressional reportcard

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#214]
┆Issue is synchronized with this [Trello card](https://trello.com/c/DhQ53FmG)

**Comment by mraisle** [comment]
Here's a draft outline and some questions Cole and I are thinking about: https://docs.google.com/document/d/1PZ6baK92dU3WMWRbUl5HoHdAuPPHYmUUGIE_NTV_AD8/edit?usp=sharing
Please provide comments in this document :)

**Comment by mraisle** [comment]
@saraannwylie @crgreenleaf Will you review the above document?

**Comment by mraisle** [comment]
Let's meet with Sarah Pardo and circle back to this
