### ISSUE TITLE
test sunrise notebook

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#215]
┆Issue is synchronized with this [Trello card](https://trello.com/c/mrWxi6vh)

**Comment by ericnost** [comment]
Not sure what we mean, but here is a draft: https://colab.research.google.com/drive/1PQjT5Y4k8rPG5HqwZ5cR5nRi8Yi7DIg7#scrollTo=1B8cUhYWQDqf

This one may or may not be run-able. I'll share that shortly. Been experiencing some issues.

**Comment by crgreenleaf** [comment]
@ericnost are you looking for final feedback before we send this over?

**Comment by ericnost** [comment]
@crgreenleaf Hmm...I'm not sure what you mean by send it over? It would be best to clarify the partnership process first...I ran this with Sarah P on Thursday and got good feedback - I think we need more on our end (and Sunrise's too) before a second and/or final version. https://github.com/edgi-govdata-archiving/ECHO-Sunrise/issues/7 Unfortunately, there are some serious bugs to work that limit our ability right now to share a workable notebook widely, but you could share this first draft with outputs (it's what Sarah P saw). https://colab.research.google.com/drive/1PQjT5Y4k8rPG5HqwZ5cR5nRi8Yi7DIg7#scrollTo=1B8cUhYWQDqf

**Comment by mraisle** [comment]
Made my notes a google doc b/c github was not pleased with copy/paste: https://docs.google.com/document/d/1gc6Hv8x30VUhKiURS2L-LXoMRL8UtmRD8IJ0QhtTGOg/edit?usp=sharing

**Comment by crgreenleaf** [comment]
@ericnost I got confused, makes sense!

**Comment by ericnost** [comment]
Here's a run-able version! https://colab.research.google.com/github/edgi-govdata-archiving/ECHO-Sunrise/blob/master/ECHO-Sunrise.ipynb
