### ISSUE TITLE
Edit storytelling deck for track

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#216]
* [ ] Get feedback
* [ ] edit according to feeback
https://docs.google.com/presentation/d/1h-xdL1BVM90yxvPplCumFcfZsqbOWbCAbCgSOAd2KpY/edit#slide=id.g8a6a8961be_0_63

┆Issue is synchronized with this [Trello card](https://trello.com/c/7TRl2LHR)

**Comment by lesliealanis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Edit storytelling deck for track #216](https://trello.com/c/htYbfqE9/82-edit-storytelling-deck-for-track-216)

**Comment by lesliealanis** [comment]
https://docs.google.com/presentation/d/1h-xdL1BVM90yxvPplCumFcfZsqbOWbCAbCgSOAd2KpY/edit#slide=id.g8a6a8961be_0_63
