### ISSUE TITLE
Intro Intern Blog Post

### ISSUE THREAD

**Issue by gabrielletrudo** [edgi-govdata-archiving/EEW_Planning#218]
Interns Answer 3 Qs by July 8th! https://docs.google.com/document/d/1SxPC560VkAptTBXWSLdjOaEG0o4y2kbQMjaSTpXYgDs/edit

┆Issue is synchronized with this [Trello card](https://trello.com/c/QDo4vTs3)

**Comment by lesliealanis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Intro Intern Blog Post #218](https://trello.com/c/cg24Fnl8/84-intro-intern-blog-post-218)

**Comment by crgreenleaf** [comment]
Completed 👍

**Comment by mraisle** [comment]
Done! Thanks Gabby :)

**Comment by lourdesvera** [comment]
@gabrielletrudo how is this going?

**Comment by lourdesvera** [comment]
We did it!
