### ISSUE TITLE
Python Basic Commands

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#22]
[Python Basic Commands](https://drive.google.com/open?id=1K8yoU2C17erWQyvzY0ob_R5g8GcJutpf0G9agM2lGDI)

┆Issue is synchronized with this [Trello card](https://trello.com/c/eC89LCDj)

**Comment by Frijol** [comment]
Do we still want this? I don't think it really suits our current vision for the data science track
