### ISSUE TITLE
Create Mural for (Sunrise?) Storytelling Event

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW_Planning#225]
this is just a place to put the mural for review

┆Issue is synchronized with this [Trello card](https://trello.com/c/WiYoK5AV)

**Comment by lesliealanis** [comment]
linked with issue #216 since #216 is the non-mural version of the storytelling event, #216 is more of a conversational format than an interactive format

**Comment by lourdesvera** [comment]
@crgreenleaf can we have a meeting next week to work on storytelling with @lesliealanis?

**Comment by lesliealanis** [comment]
link to mural: 
https://app.mural.co/invitation/mural/managementworkshops7524/1593052252947?sender=lesliealaniscazares6748&key=46482aea-ec4c-4f34-8099-b15517292a65
