### ISSUE TITLE
Compile run of show document

### ISSUE THREAD

**Issue by crgreenleaf** [edgi-govdata-archiving/EEW_Planning#228]
┆Issue is synchronized with this [Trello card](https://trello.com/c/j9i7G1bH)

**Comment by saraannwylie** [comment]
https://docs.google.com/document/d/1kg7L2Glx7M140CaTcwx3pzVT0DUwfb7C9L7apQoIXew/edit#

See here

**Comment by saraannwylie** [comment]
To do list for this doc:

- [ ] Add feedback table for after breakout 1 (sara w to draft)
- [ ] Add/check links to Data Vis materials (@lourdesvera 
- [ ] Add/check links to Story telling materials @lesliealanis 
- [ ] Add/check links to Notebook @ericnost 
- [ ] Add/check links to breakout group slide decks (Sara)
- [ ] Add/check links to congressional district report @mraisle 
- [ ] Add/check links to research and contextualization @calderEDJ and @mraisle 
- [ ] Remove unnecessary materials @crgreenleaf 
- [ ] Make a back up copy @crgreenleaf

**Comment by saraannwylie** [comment]
List for activities in run of show:

- [ ] Check if we can make multiple zoom hosts
- [ ] Test break out group sign up
- [ ] Test green house gas demo and data gathering

- [ ] Test moving into break out rooms
- [ ] Test chatting in break out rooms -do we use zoom or slack?
- [ ] Test running notebooks at same time 
- [ ] Test moving findings to the working group slide deck
- [ ] Try saving data into the right folder

- [ ] Test updating congressional reports with additions to working group slide deck
- [ ] Try report back
- [ ] Test feedback form filling out

- [ ] Try second break outs

**Comment by saraannwylie** [comment]
Great work going through the rehearsal yesterday here's my list of remaining to dos based on the feedback throughout--Things to add here? Or assignments to change? Hope this list isn't overbearing!!

**[Intro](https://docs.google.com/presentation/d/1dTli9mghTIhFOFLVHDp1m84pGlLXckg3/edit#slide=id.g8c23d18a2d_1_0)**
- [ ] Revise and update Intro @crgreenleaf and @saraannwylie 

- Make the goal of making the congressional district reports more clear, Have Sarah Pardo introduce Sunrise goals
- [ ] Explain sign for breakout groups before the green house gas demo
- Make language more transparent (e.g. hazardous waste vs. RCRA)
- Revise ECHO description slide, add screenshot, “are visible” is confusing w/o context of the ECHO portal all of it is downloadable, only 3-5 are accessible through EPA-provided UI
- Refine wording "poorly for non experts"
- Revise Stonybrook graphic or explain more clearly: Sarah Pardo: I think the graphic explaining how the stony brook servers work might be a little overwhelming for non-coders, people who are unfamiliar

- [ ] Practice the GHGRP Demo @maalvikabhat (@saraannwylie happy to practice with you)
Notes on this
- Pre-run note book
- Run a few cells to show people how it works
- Tell folks what a library is
- Call out a key piece of info.
- Show how to change the congressional district
- Show how to change the program
- Show how to screen shot data and move to Congressional district primer
- Show how to save data

- [ ] Run and fill out the GHGRP data for MA 4 and MA 8 in the congressional district reports (@mraisle @calderEDJ)

**Session 1 Breakout groups**

- [ ] Based on [Allison's feedback](https://edgi.slack.com/archives/C6SA82XB3/p1594932913302600) make clear instructions doc for breakout groups @saraannwylie What data to gather and why, how to organize the break out session.
- [ ] Review that with breakout leads @calderEDJ @mraisle 

**Story Telling**
- [ ] Revise small changes to story telling track @lesliealanis 
- Typo on listening
- for group agreement, assume good intentions & also take accountability for any mess ups
- should be a bit careful re fair use of images but maybe not important unless to be used in a report? Add caution about using fair use images

**Data Vis**
- [ ] Finalize data vis primer @lourdesvera 
- [ ] organize quotes and images for storytelling track @lesliealanis and @gabrielletrudo and pass to @lourdesvera 

**Data Sci**

- [ ] Clarify language about the Data Science track in the [Event Getting Started Doc](https://docs.google.com/document/d/1kg7L2Glx7M140CaTcwx3pzVT0DUwfb7C9L7apQoIXew/edit#) @shansen5 @maalvikabhat 
- [ ] Prep any materials needed for that track? @shansen5 @maalvikabhat 
- [ ] Clarify description of that track in the [Workshop slide deck](https://docs.google.com/presentation/d/1dTli9mghTIhFOFLVHDp1m84pGlLXckg3/edit#slide=id.g8c23d18a2d_1_0)

**Research and Context**
- [ ] Finalize program primers @mraisle @calderEDJ @saraannwylie to help review
- [ ] Add links to them in the getting started doc  @mraisle @calderEDJ
- [ ] Add links to them Congressional district reports  @mraisle @calderEDJ

**Wrap Up**
- [ ] Add slide telling folks to follow us on twitter for outcomes and check the EDJ slack (@crgreenleaf) 
- [ ] Add slide with prompt to take the exit survey (@crgreenleaf) 

**[Finalizing Getting Started doc](https://docs.google.com/document/d/1kg7L2Glx7M140CaTcwx3pzVT0DUwfb7C9L7apQoIXew/edit#)**
- [ ] Make sure correct notebook link in place @ericnost 
- [ ] Make sure correct link to storage folders are in place @lourdesvera 
- [ ] Make sure all roles are filled @saraannwylie 
- [ ] Add social media suggestions doc to the getting started doc @saraannwylie 
- [ ] Make a copy @crgreenleaf 
- [ ] Make sure all fields are clear following our run of show @crgreenleaf

**Comment by saraannwylie** [comment]
@calderEDJ @mraisle How does this sound for clearer direction on what's happens in the first breakout?

@Cole @Megan R How does this sound for clearer steps for the breakout sessions? To divide up the work?
Step 1: Working as a group run the notebook for District 4 and fill out slides 4 and 5 together. 
Step 2: Divide up slides 6-10 and fill them in (add your name to slide you worked on).
Step 3: Review slides 5-10 together and fill out slide 11 with your key findings.  
Step 4: Move on District 8 divide up slides 13-19 and fill them out.
Step 5: Reflect on slides 13-19 together and fill out slide 20
Described in [slide 3 here ](https://docs.google.com/presentation/d/1nZv5t-M3fKBi5RlGkblDT2qt5iX7TCJw0NHvC0h8yKI/edit#slide=id.p)

**Comment by saraannwylie** [comment]
@mraisle and @calderEDJ just made the above change to all the program breakout slides
