### ISSUE TITLE
Send out pre-event email to registrants

### ISSUE THREAD

**Issue by crgreenleaf** [edgi-govdata-archiving/EEW_Planning#230]
- [ ] Draft/review email
- [ ] Collect emails from registration
- [ ] Send email night before
- [ ] Rename & create Sunrise Slack channel in EDJ slack

┆Issue is synchronized with this [Trello card](https://trello.com/c/yaNGun75)

**Comment by Frijol** [comment]
From [Sunrise Event Planning Doc](https://docs.google.com/document/d/1kg7L2Glx7M140CaTcwx3pzVT0DUwfb7C9L7apQoIXew/edit?ts=5f089884#)

Send onboarding email to registrants with:
Slack invitation
Start here primer to look over
Request that they
Read code of conduct prior to attending
Join the Slack prior to attending
Introduce themselves in the Slack prior to attending 
Anything they might want to bring to the event?
