### ISSUE TITLE
EEW landing page edits

### ISSUE THREAD

**Issue by calderEDJ** [edgi-govdata-archiving/EEW_Planning#231]
* [x] home page, link hyperlink needs fixing (What is a Jupyter notebook [hyperlink]).
* [x] about page Green Roots is GreenRoots
* [x] It doesn't look like this document about juypter notebooks ready to share (linked on about page) "https://docs.google.com/document/d/1fAWoUbsISSV-tFZvASbTDE6KRl6Hkeu4p-N2jpQFmt0/edit". suggest substituting with a link to https://jupyter.org/
* [x] don't know if we can share the reading pdfs without violating copyright, suggest instead we just link to the EDJ syllabus. And revise the text to say "You can read more about EDJ in this syllabus" https://docs.google.com/document/d/1O7ytnzXWFkluiYE4Pulo_mCHs9jdNpPm8hw83aLU2pg/edit#heading=h.pfx5h5bzvu6q
* [x]  we can now include a link to the 2020 Annual report. Add in about page section and on menu dropdown
* [x] In "work with community organizers, concerned residents, university students and staff to dive into the data and stories in your legislative districts, zip codes, a to find out", 'a' should be "and counties"? Neighborhoods?
* [x] make sure the text is all open sans, change the red links to EDGI secondary colors (magenta), and make the text on the about page darker.
* [x] in the quote ("In these virtual workshops...") I think it should read ...concerned residents, and university students and staff.... Otherwise it's unclear what "staff" refers to.
* [x] “cross-working group project” is a little awk to me, could we say “interdisciplinary collaboration between EDGI’s x number of working groups” or something like that?
* [x] “However, they also revealed how inaccessible ECHO is for non-specialists and that there are many omissions, errors, and confusing aspects of the ECHO data.” --> “…reveled the inaccessibility of ECHO for non-specialists as well as the many omissions, errors, and confusions present in the data itself.” 
* [x] “The EEW events aim to make ECHO data more readily accessible and meaningful for impacted communities while highlighting how ECHO data could *can* be improved.” Set in bold!
* [x] change funding section to look like rest of secitons
* [x] Add report making svg

┆Issue is synchronized with this [Trello card](https://trello.com/c/p0q4EbD1)

**Comment by saraannwylie** [comment]
Should we add something that credits @calderEDJ with the video music and @crgreenleaf with the video production? Should we add a line that credits those who designed the website @lourdesvera in particular?

**Comment by ericnost** [comment]
+100

**Comment by lourdesvera** [comment]
> Should we add something that credits @calderEDJ with the video music and @crgreenleaf with the video production? Should we add a line that credits those who designed the website @lourdesvera in particular?

in the youtube description we need to credit Casey too

**Comment by saraannwylie** [comment]
Hey all Kelly just shared some thoughts on the EEW landing page:

- [ ] The EDGI logo is blurry, 

- [ ] the social icons aren’t the same size, 

- [ ] there’s spaces between the words in one of our hashtags, and 

- [ ] there’s a few layout things too, but most importantly I think it would be better to have a better layout for the tracks. The way the icons and text is organized is a bit disorderly. If there’s a way to make them look more like this (the icons could go under the report making section) I think that would improve it a lot.
<img width="424" alt="Screen Shot 2020-07-09 at 10 32 27 AM" src="https://user-images.githubusercontent.com/8268933/87072647-270ea280-c1ea-11ea-924e-6ba5eafb1f72.png">

**Comment by lourdesvera** [comment]
maybe we need to just find new social media icons. The ones we have are hard to re-size and make the same size since they all come in different dimensions.

**Comment by lourdesvera** [comment]
The reason the tracks aren't laid out like that are because this is what it looks like on a tablet: 
![image](https://user-images.githubusercontent.com/23300449/87086539-c1c5ac00-c1ff-11ea-88da-e2f7a5877d58.png)
