### ISSUE TITLE
Write blog post that introduces EEW and includes 5 goals

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#233]
Goals are here: https://app.mural.co/t/managementworkshops7524/m/managementworkshops7524/1590629229746/f4980a794a1ec62cc327df36e31578881e5441c6

@gabrielletrudo is this a duplicate of an existing issue to make an EEW intro blog post?

┆Issue is synchronized with this [Trello card](https://trello.com/c/Wh0LUXRx)

**Comment by Frijol** [comment]
Working on wording for goals here https://github.com/edgi-govdata-archiving/EEW_Planning/issues/234

**Comment by gabrielletrudo** [comment]
We introduced EEW in the Interns blog post but didn't go into depth about our goals. Do we still want to do this? I am happy to take the lead on this one and put together an Intro to EEW post. Maybe include more info on the non-interns/coordinators to 'introduce' the rest of the team as well. Let's discuss briefly during the planning meeting.

**Comment by Frijol** [comment]
Yes, I still think a blog post outlining what EEW is and its goals would be a good idea! (Personally don't think the team introduction is as important as discussion of the project + a call to action inviting people to participate)
@ericnost @lourdesvera @saraannwylie sound good to you?

**Comment by saraannwylie** [comment]
@gabrielletrudo has started work on this to my knowledge she is wondering which goals to base it around [see](https://edgi.slack.com/archives/C014PBR66BH/p1597072871002000)

**Comment by gabrielletrudo** [comment]
really bare bones, working on it more Wednesday and Friday: https://docs.google.com/document/d/1y7o4Ynj0r9RQWQ2vX4PUJHhfj-pt12Yw_WSyvhLbEBc/edit
