### ISSUE TITLE
Set up EDJ Slack

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#235]
From Sunrise Event [Main Doc](https://docs.google.com/document/d/1kg7L2Glx7M140CaTcwx3pzVT0DUwfb7C9L7apQoIXew/edit?ts=5f089884#)

Set up EDJ Slack
		Rename?
Should we make an EEW channel to the EDJ
Amend title to EDJ@EEW
		Make Sunrise channel?
		Invite participants
			When?
			Friday/Thursday?
		Check people actually join?

Also relevant: https://www.google.com/url?q=https://github.com/edgi-govdata-archiving/EEW_Planning/issues/27&sa=D&ust=1594754465843000&usg=AFQjCNFh6Soti50ESAkJ1bwAyuI3H4gRWQ

**Comment by crgreenleaf** [comment]
Slack made! I plan to invite participants to join at the end of today (Wednesday) to leave time for troubleshooting
