### ISSUE TITLE
Tweet about Sunrise EEW event

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#237]
From [Sunrise Event Planning Doc](https://docs.google.com/document/d/1kg7L2Glx7M140CaTcwx3pzVT0DUwfb7C9L7apQoIXew/edit?ts=5f089884#)

Tweet about event
When
Who
What should we say?
Sarah Pardo from Sunrise can review any tweets before they’re sent.

**Comment by gabrielletrudo** [comment]
https://twitter.com/EEW_Network/status/1284131637756866561
