### ISSUE TITLE
Figure out where outputs from different tracks should go

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#24]
Currently thinking:

## Local info
* Each location will output a report (report template includes this instruction
* Each report has a section for outputs from each track working on that area, participants paste in content and links as they make them

## Overarching outputs
* There is also a template doc for the whole event with spaces for each track to paste into + a spot for pasting of links to location docs (this is to make sure there's one master doc so we don't lose anything)
* Any modifications to existing notebooks should be uploaded as **pull requests** on the existing notebook
* Not sure if there is a need to make a catch-all repo for any additional code (dataviz or new notebooks)—maybe let's make that if it comes up

┆Issue is synchronized with this [Trello card](https://trello.com/c/yHlx6SUj)

**Comment by ericnost** [comment]
As someone who fell behind with the development of this project, it's unclear to me what the bigger picture of outputs might look like. Currently it sounds like: a Google Drive worth of reports and copied notebooks that maybe make it onto the website at some point? I may have missed this part of the conversation...but I have some ideas about what a public-facing collation of outputs might look like. I'm particularly partial to map-based interfaces given that's how a lot of the tracks are set up (congressional district, state, zipcode, etc.)

**Comment by saraannwylie** [comment]
For the stonybook event we decided participants should copy and save a local copy of their notebooks and drop a url for their copy into to their track note book. I also made a folder for the CSVs [folder for the CSVs:](https://drive.google.com/open?id=1RiOxrYq4TkhfOZwvBws58cP-K4GtA_iP)
