### ISSUE TITLE
Make Breakout session 1 slide decks for each program

### ISSUE THREAD

**Issue by saraannwylie** [edgi-govdata-archiving/EEW_Planning#240]
These google slide decks will be used in each program break out session in the first half of the workshop.

I drafted a full template here with space for reports for 1 program for 3 congressional districts:
https://docs.google.com/presentation/d/1Qf3_j8hwjc5TXgWaX_uzpCgRtLbDmJr6SdMZK-LEGKw/edit#slide=id.g8d8e06c901_0_98

**Comment by saraannwylie** [comment]
- [ ] Template needs a review by breakout leads @mraisle @crgreenleaf @calderEDJ 

- Once reviewed template needs to be copied and customized to each program breakout group to add the program name throughout and district number, link to notebook and link to google drive data folder.

- [ ] CWA customized, 

- [ ] CAA customized

- [ ] RCRA customized


- [ ] Once customization is complete breakout group slides need to be linked into the congressional report slide deck for each district. See issue #241.

- [ ] Each slide deck needs to be added to the event welcome getting started doc.

- [ ]

**Comment by ericnost** [comment]
This is quite impressive. Seeing it laid out like this, however, makes me wonder if we're asking too much of each breakout. But, if they only get 1 district, that's ok. Perhaps we could customize a version with example output so people know what they're aiming for?

**Comment by saraannwylie** [comment]
Agreed I think it's probably too much to hope for folks to work through more than 2 districts.

**Comment by mraisle** [comment]
Here are the customized links for each program. They still need the link to the notebook, link to google drive data folder, and an example slide for GHGRP: 
CAA - https://docs.google.com/presentation/d/1nZv5t-M3fKBi5RlGkblDT2qt5iX7TCJw0NHvC0h8yKI/edit?usp=sharing
CWA - https://docs.google.com/presentation/d/1UgAZ7EZBBNiuAw4p7eQtH7jRmScpQsw9w_4CTGE1hgM/edit?usp=sharing
RCRA - https://docs.google.com/presentation/d/1mWHccd4xAwsMvLY1MHLNt-Sge0b7coPg4pANEZf1NOA/edit?usp=sharing

**Comment by mraisle** [comment]
^link above are most final version, all that's needed it link to data folder
