### ISSUE TITLE
Make congressional report slide decks for the Sunrise event that will contain the results from the breakout groups

### ISSUE THREAD

**Issue by saraannwylie** [edgi-govdata-archiving/EEW_Planning#241]
Once the breakout are complete we'll compile their results into congressional report deck for districts 4, 7 and 8 in Ma. These need to be linked to the breakout session slides ahead of time. see issue #240

**Comment by saraannwylie** [comment]
I've not started this as I'm not sure if @mraisle is already working on it.

**Comment by mraisle** [comment]
Link to current draft: https://docs.google.com/presentation/d/1516-Iki_2TB-P0ifXmhpfYMsbITIaGpoTjbSkLX33TA/edit?usp=sharing

**Comment by mraisle** [comment]
^ after folks have edited and reviewed this, we can start linking slides to the appropriate Breakout 1 Program slides

**Comment by saraannwylie** [comment]
Great start @mraisle I gave the template a thorough read.

**Comment by mraisle** [comment]
District 4 Slide Deck: https://docs.google.com/presentation/d/14wJod7YY_tHQnxH7ykh8fgMhDQvd3RqT5QsYucsqxUk/edit?usp=sharing

District 8 Slide Deck: https://docs.google.com/presentation/d/1_ahugjy24yp3D1DHaf1CxgDoplkFePAz8Sg9Y-Ls974/edit?usp=sharing

**Comment by mraisle** [comment]
Cole and I are working on linking slides now

**Comment by mraisle** [comment]
Final Slide Decks: 
District 4 Slide Deck: https://docs.google.com/presentation/d/14wJod7YY_tHQnxH7ykh8fgMhDQvd3RqT5QsYucsqxUk/edit?usp=sharing

District 8 Slide Deck: https://docs.google.com/presentation/d/1_ahugjy24yp3D1DHaf1CxgDoplkFePAz8Sg9Y-Ls974/edit?usp=sharing

closing this issue!
