### ISSUE TITLE
Data analytics - oriented notebook

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#243]
Prototype a notebook/part of notebook that takes a more data science analytical approach e.g. looking for correlations - Kelsey (unless someone else is excited to)

**Comment by Frijol** [comment]
Hm, I don't think I'm going to get around to this in the next couple of weeks/maybe let's throw it onto the "someday" pile

**Comment by Frijol** [comment]
@lourdesvera is this an issue we still want to keep around?

**Comment by Frijol** [comment]
actually I see I was the one who suggested it so I'll close
