### ISSUE TITLE
Test cross-program notebook using Postgres

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#245]
Test out the cross program notebook using Postgres.

https://colab.research.google.com/github/edgi-govdata-archiving/ECHO-Cross-Program/blob/database-views/facility-all-programs.ipynb

Compare your experience to the original notebook and comment on this issue: 
@maalvikabhat can you drop the link here?

Should we tag 3- 4 people to do this?

**Comment by ericnost** [comment]
Steve has led development of this and we have been testing it.
