### ISSUE TITLE
Make a website persona

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#250]
In mural: https://app.mural.co/t/managementworkshops7524/m/managementworkshops7524/1595348408275/edb9862bfe6e66711f6e4b2509a3d1e5c7794dfc

Use template, try to think of a user not already covered in a different persona

**Comment by Frijol** [comment]
cc @ozzmotic

**Comment by gabrielletrudo** [comment]
I did one last week so I'll be unassigning. If I need to do another one, reassign me!

**Comment by crgreenleaf** [comment]
Done!
