### ISSUE TITLE
Create public hour registration & social media promotional posts

### ISSUE THREAD

**Issue by crgreenleaf** [edgi-govdata-archiving/EEW_Planning#251]
- [x] Registration

- [x] Social posts

**Comment by gabrielletrudo** [comment]
This ties in with #256 as we can use COVID report promo as a jump off and then continue from there

**Comment by crgreenleaf** [comment]
The registration link can be found at bit.ly/EEWNetwork

**Comment by gabrielletrudo** [comment]
Promo Post Drafts in Comms Spreadsheet (https://docs.google.com/spreadsheets/d/18YDcV4GoxGlEU9yYA8069ozKFtiH4bED6Wymjpmv8QM/edit#gid=1050155861) under social posts for EEW
