### ISSUE TITLE
Develop social media strategy in connection with COVID report outreach

### ISSUE THREAD

**Issue by crgreenleaf** [edgi-govdata-archiving/EEW_Planning#256]

**Comment by gabrielletrudo** [comment]
Drafting tweets for EDGI re: COVID report so I can do some for EEW as well! Craft language to introduce next Thursday's (8/6) public hour event. Would be great to get some clarity on what exactly the focus will be for that event, seems like that'll be decided by this Thursday (7/30).

**Comment by gabrielletrudo** [comment]
Draft tweets for EDGI COVID report are here: https://docs.google.com/spreadsheets/d/18YDcV4GoxGlEU9yYA8069ozKFtiH4bED6Wymjpmv8QM/edit#gid=1549759825

Potential to use the EEW description in the COVID report to promote public hour on the EEW page or the EDGI page. Excerpt to work with is:

"The data that we have been collecting and analyzing to answer questions about EPA enforcement during COVID has been part of EDGI’s ongoing project, @EEW_Network. We are coordinating a series of workshops that use ECHO data to address community-based and nation-wide questions..." // "about environmental enforcement. EEW looks at whether ECHO data can answer these questions and how other forms of knowledge like storytelling, data visualization, and research can provide more context to this data. <link>"
