### ISSUE TITLE
Finalize track descriptions

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#26]
Finalize track descriptions and names

┆Issue is synchronized with this [Trello card](https://trello.com/c/tRQBowur)

**Comment by Frijol** [comment]
Did we finish this? I suspect yes (cc @lourdesvera @saraannwylie @crgreenleaf @calderEDJ )

**Comment by calderEDJ** [comment]
Is this referring to the track descriptions on the website? I think those are done

**Comment by lourdesvera** [comment]
We are done, might need some edits but that has to do with website landing page copy.
