### ISSUE TITLE
Develop google slides about this project

### ISSUE THREAD

**Issue by crgreenleaf** [edgi-govdata-archiving/EEW_Planning#260]

**Comment by ericnost** [comment]
Didn't Casey develop a template? Don't we have existing presentations to pull from in the Google Drive?

**Comment by crgreenleaf** [comment]
I did! It's in the Google drive! https://drive.google.com/file/d/12kL7hEhVluk6cS3p8QkLHoam80dd_0-U/view?usp=sharing
