### ISSUE TITLE
Talk proposal for SeaGL

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#265]
via @shansen5 

---
SeaGL's Call for Proposals opened today! Please help us spread the word
and also consider submitting a proposal or three :).

As usual, SeaGL welcomes new speakers! This year we're looking for tech
talks, culture talks, performance art and, of course, FLOSS topics :).

For this year's virtual conference format talks are 20 minutes with 10
minutes for Q&A.

We will once again hold office hours if you'd like some help or
encouragement for your talk proposals. The office hours are every
Wednesday at noon Pacific between July 22 and August 19 in the #SeaGL
IRC channel on Freenode.

https://SeaGL.org/news/2020/07/14/CFP-open.html

cfp closes August 19th

SeaGL is November 13th - 14th

Mastodon post: https://mastodon.social/@SeaGL/104519869578696312

**Comment by shansen5** [comment]
I'm still interested, just slow.  
I was wondering whether EDGI would want to do a presentation that is a combination of the web archiving and EEW ECHO work?  Or propose two presentations?

**Comment by Frijol** [comment]
Probably would make more sense to propose one for EEW and one for Web Monitoring separately, @Mr0grog are you interested in giving conference talks?

**Comment by Mr0grog** [comment]
Sure! Agree they should probably be separate talks if we wanted to cover things about both topics/project areas. I just haven’t really felt like I had any good ideas about things to talk about w/r/t web monitoring. And obviously I would not be a good person to talk about anything to do with EEW.

**Comment by Frijol** [comment]
@shansen5 correct me if I'm wrong but I think the idea on the WM side was to talk about the parts of Scanner that got adopted into the Internet Archive

And then Steve is up for speaking on EEW in a separate talk

**Comment by mraisle** [comment]
I saw in slack that @shansen5 submitted this. Close this issue?

**Comment by Mr0grog** [comment]
Did that include a proposal for Web Monitoring?

**Comment by Frijol** [comment]
Oh whoops sorry @Mr0grog no I think that would be separate! Are you planning to submit one?
