### ISSUE TITLE
Outreach to society for environmental journalists for meeting

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#269]

**Comment by crgreenleaf** [comment]
Now in communication with the Institute for Environmental Journalism, but a guy from the Institute for Journalism & Natural Resources reached out to ask for our participation as they are conducting a two-day virtual workshop in October aimed at getting reporters up-to-speed on the Trump Administration's efforts to reshape the EPA and the real and potential consequences of those efforts and what is at stake in our next election.

"We are hoping to not just put a bunch of sources and story ideas on journalists' radar, but also offer some training on how to follow these developments and what's going on at a state-level where they live. We think the EEW would be a perfect tool for this. We will have 25 participants from newspapers, radio stations and online platforms all over the country and we would be thrilled if you could find the time to help us set something up. I don't know if this is something a single person could pull off, or maybe we invite a journalist who has used the platform to also talk about its utility, etc. - we're definitely still open to ideas!"
