### ISSUE TITLE
Announce the events on the EDJ slack

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#27]
Create message for EDJ slack AFTER the landing page is finished. This message will be sent to all the members to announce the events and let them know that we will be using the slack for the public facing portion of the events.

┆Issue is synchronized with this [Trello card](https://trello.com/c/UHKAVyVr)

**Comment by lourdesvera** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Project Description Slides](https://trello.com/c/ftXD9dlM/1-project-description-slides)

**Comment by Frijol** [comment]
held up by https://github.com/edgi-govdata-archiving/EEW_Planning/issues/6

**Comment by Frijol** [comment]
Does this issue still make sense? I suspect we will have several different events to announce, maybe we should close this issue & open one as it becomes relevant?
