### ISSUE TITLE
Having a report card review meeting to review existing report cards/data check or grading system? Sept 17

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW_Planning#318]
I'm unsure whether this meeting is to review and finalize the report card format/ grading, or to review/data check existing report cards
we need to make sure:
- Address senator/statewide report cards differences
- District in comparison page needs to be different

**Comment by ericnost** [comment]
On the 9/17 meeting we will have a break out in which @shansen5  will demo the report card notebook. This will be transcribed. @maalvikabhat  will edit for clarity and translate into markdown to add to the notebook itself.
