### ISSUE TITLE
Finalize what should be in a data check: Sept 21

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW_Planning#320]
Finalizing a step by step procedure for data checking report card drafts

**Comment by ericnost** [comment]
Two parts:
1. A thorough data review on 1-3 report cards
- [ ] ?
- [ ] ?
2. A visual gut check on each and every report card as it is produced (see #330)
- [ ] Does the number of facilities reported make sense?
- [ ] Is the text right (e.g. if the district is in WA, does all the text reference WA and not some other state?)
- [ ]

**Comment by Frijol** [comment]
Adding myself and @shansen5 and @maalvikabhat to this issue

**Comment by ericnost** [comment]
Part 1 - testing OR2 https://colab.research.google.com/drive/13MIGC-FGgkLe2HFQeXN-andKYijVksju?usp=sharing
- [x] Were program records found for each program? 
- [x] Cell 6 - does the CSV accurately reflect state facilities. Are there facilities not in this state?
- [x] Cell 7 - check State and CD active facilities by program by sorting the output in Cell 6 in Excel. Use DERIVED_CD113, FAC_ACTIVE, AIR_FLAG, etc. columns
- [x] Cell 9 - use output CSV to check. Do for CD2 and assume state data is fine. Use CAA_3YR_COMPL_QTRS_HISTORY as a test and assume all else is fine. This is laborious to calculate in Excel! Use Len/Substitute functions to look for "S" and "V" in  CAA_3YR_COMPL_QTRS_HISTORY then sum.
- [x] Cell 10 - download CSV and sum by YEARQTR. Make sure it matches output. First convert to year by dropping last number from YEARQTR. Then create pivot table. Did this for CD2, assumed state is fine.
- [x] Cell 10 - CD values are less than state
- [x] Cell 11 - download CSV for RCRA inspections for CD2 and assume other metrics are ok, state data is ok. Use EVALUATION_START_DATE column. Reformat to year. Create pivot table. Do count of EVALUATION_START_DATE.
- [x] Cell 12 - CSV for CAA penalties for CD2. Reformat to use on SETTLEMENT DATE Column. Insert pivot table. Count this for number of inspections, sum PENALTY_AMT for total $. 
- [x] Cell 13a - Confirm that the # of active facilities for each program matches previous output in cell 7.
- [x] Cell 13a - Download CWA Inspections for the CD, count the inspections for 2019, divide by number of active NPDES facilities confirmed earlier, and x 1000. Use ACTUAL_END_DATE column
- [x] Cell 13b - assume that if 13a (2019 inspections) is right, 13b is right (2001+ inspections per 1000).
- [x] Cell 14 - Confirm that the # of active facilities for each program matches previous output in cell 6.
- [x] Cell 14 - Download CAA Inspections for the state, count the inspections for 2019, divide by number of active Air facilities confirmed earlier, and x 1000. Use ACTUAL_END_DATE column.
- [x] Cell 15a - Confirm that the # of active facilities for each program matches previous output in cell 7.
- [x] Cell 15a - Download RCRA Violations for the CD, count the violations for 2019, divide by number of active RCRA facilities confirmed earlier, and x 1000. Use DATE_VIOLATION_DETERMINED column
- [x] Cell 15b - assume that if 15a (2019 violations) is right, 15b is right (2001+ violations per 1000).
- [x] Cell 16 - Confirm that the # of active facilities for each program matches previous output in cell 6.
- [x] Cell 16 - Download CAA Violations for the state, count the violations for 2019, divide by number of active Air facilities confirmed earlier, and x 1000. Use the Date column.
- [ ] Cell 17 - TBD
- [ ] Cell 18 - TBD
- [x] Cell 20 - Use ECHO_EXPORTER table downloaded from Cell 6. Sort / compare the counts made for Cell 9 verification. RCRA_3YR_COMPL_QTRS_HISTORY column.
