### ISSUE TITLE
Draft tweets about report card release Oct 9

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW_Planning#324]
Draft tweets about report card release
    - Make sure to include sample tweets for inquiring orgs: see COVID Report issues

**Comment by saraannwylie** [comment]
@calderEDJ I think the highlight from the reportcards will make good tweets, I am also happy to help on this

**Comment by crgreenleaf** [comment]
Also would be good to have some sort of "we're making these" stay tuned

**Comment by saraannwylie** [comment]
@crgreenleaf can you update this issue with a spreadsheet that has the tweets you've developed in it? And think on the timeline for releasing them?

**Comment by crgreenleaf** [comment]
https://docs.google.com/spreadsheets/d/1Xy4kg3fJu01W7e_jL3v5olbBBNWAvrkKZ34XNnG45Qc/edit#gid=1598330758
