### ISSUE TITLE
Post blog about Report Card project Oct 19

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW_Planning#326]
posting the blog from #325 in EEW Website

**Comment by saraannwylie** [comment]
Let's figure out whose going to write this, a due date and get make the space for it on the EDGI website? @calderEDJ any chance you could lead this? And how about next Friday the 2nd as deadline for a draft? It doesn't have to be long and could borrow a lot from the press release. Also it will be shared with the enforcement report, so it could just be the front page of that.
