### ISSUE TITLE
Release report cards under embargo Oct 14

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW_Planning#328]
Releasing all report cards under embargo by oct 14

**Comment by crgreenleaf** [comment]
I can do this but I'll need some guidance @saraannwylie

**Comment by saraannwylie** [comment]
- [ ] Organize embargo journalist list @gabrielletrudo can you work with @crgreenleaf so she has this before you leave?

- [ ] Draft email to release with embargo

- [ ] Figure out exactly what we'll release e.g. can we release the website under embargo? Are we sending pdfs. Need to settle relatively soon.

- [ ] Draft pressrelease
