### ISSUE TITLE
Make report cards public and deliver them to congress people Oct 19

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW_Planning#329]
Making report cards public and delivering them Oct 19 linked to #328

**Comment by saraannwylie** [comment]
let's have a conversation soon about how to do this with sunrise and UCS? @crgreenleaf

**Comment by crgreenleaf** [comment]
I think this should include tagging the congresspeople on twitter, emailing them and their staffers, and possibly trying to set up meetings b/w them and any constituents if we have any

**Comment by saraannwylie** [comment]
I think this issue is redundant with issue 337: https://github.com/edgi-govdata-archiving/EEW_Planning/issues/337, so closing it.
