### ISSUE TITLE
Mural access

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#335]
Hello @saraannwylie @lesliealanis @lourdesvera let's get this Mural access thing figured out!

Currently we have 1 paid membership at the "starter" tier, assigned to EDGI's gmail. It cost $144 for the year ($12/month) and is good through July 21 next year. Anyone logged into the EDGI gmail can use this – so the no-extra-cost option is to spread that access to more people.

The other option is to add more memberships, also at $144 for the year or for $16/month (thanks for the research @lesliealanis). @saraannwylie has suggested we add her and Leslie. This seems fine to me, and I'm happy to do the admin for this. **Couple of questions before we go forward, though:**
* Are we ok on funding for this? Any approval process we need to move through?
* Do we want the whole-year memberships, or is a few months more appropriate?

Just as a process note, this will be billed to my credit card and then I will request reimbursement from EDGI.

**Comment by saraannwylie** [comment]
This is settled we bought 1 EDGI account. @lesliealanis do you have access to it?
