### ISSUE TITLE
Get clear on pipeline from notebook to report to website

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#336]
Possibly somebody already knows this stuff! But I'm feeling lost, so want to see if I can pull together links & notes for: How a Notebook Becomes a Report

hmm but the bits I have are:
* Overall, we build Jupyter Notebooks using Python to draw via SQL query from the SBU database. The Notebooks generate CSV files which are then passed through R scripts to generate beautiful RMarkdown reports, which are hosted in a Github repo which serves them via Github pages. Presumably, the EEW website is intended to link to/possibly embed these hosted reports. In an ideal future version, each report would also have script-generated metadata that we can feed directly into an interactive D3 visualization on the website (this is the branch where that's being attempted https://github.com/edgi-govdata-archiving/EEW-Website/tree/congress-viz)
* Here's a sample output report: https://edgi-govdata-archiving.github.io/CD-report/
* There's a document somewhere that @mraisle made that outlines a bunch of this process
* All the notebooks can be found in the [EEW Tracker](https://docs.google.com/spreadsheets/d/1Z2rBoGqb_SXW6oAu12A6TCWEJGV1pk0YxL13P_Z5Wlw/edit#gid=1601968109)
* Notebook code is hosted on EDGI's Github repos, e.g. https://github.com/edgi-govdata-archiving/ECHO-Cross-Program
* There's a data checking process, is this Github Issue the right place to follow for that? https://github.com/edgi-govdata-archiving/EEW_Planning/issues/320 cc @ericnost 
* Another thing that would be really great but that we are *not* yet doing is automated testing and/or data checking

Ideally we could pull this all together in a really great document and possibly also a diagram primarily for internal use

cc @maalvikabhat @calderEDJ @ozzmotic

**Comment by saraannwylie** [comment]
@mraisle and @Frijol how are you doing on this?

**Comment by ericnost** [comment]
I think we have all the pieces in the puzzle (a notebook demo, report-card making instructions) we just need them in a single place with maybe just a bit of additional writing to stitch them together.

FWIW, the project as is isn't really replicable. We didn't really have/take the time to plan out a data framework that would link the notebooks and R script, so there's a tedious process of compiling 31 CSVs per district (do the math for the entire project!). That would need to be a major focal point of any next step - like watershed reports - so I'm hesitant to spend time now compiling that bigger picture. Feels a bit like busy work, or is it blocking anyone?

**Comment by Frijol** [comment]
Yeah, I'm ok with closing this issue pending more replicable process

**Comment by Frijol** [comment]
@shansen5 do you think this is ok to close or is there a process we should document?
