### ISSUE TITLE
Translating report cards and jupyter notebook to Spanish 10/03

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW_Planning#339]
What I've translated so far with the jupyter notebook: https://docs.google.com/document/d/1jeE1D9JmeGidpcMLmlAbYsZPJq5kMtl4gIFoForFO-M/edit?usp=sharing

**Comment by saraannwylie** [comment]
Check list for this

- [ ] Translate reportcard text into Spanish 

- [ ] Translate figures into Spanish

- [ ] Translate the spreadsheet @calderEDJ developed on the representatives into Spainish for inclusion

- [ ] Organize review of Spanish language version of the Report cards

- [ ] Translate the enforcement report 

- [ ] Translate Website content or develop a Spanish translated page.

- [ ] Identify journalists who might report in Spanish @crgreenleaf drawing your attention to this.

- [ ] Translation for the report card release event? @lesliealanis and @crgreenleaf

- [ ] Or develop a Spanish language release event? @crgreenleaf and @lesliealanis let's discuss next week?

**Comment by lesliealanis** [comment]
[All Programs Notebook translated](https://docs.google.com/document/d/1jeE1D9JmeGidpcMLmlAbYsZPJq5kMtl4gIFoForFO-M/edit#)
[National Notebook translated](https://docs.google.com/document/d/1Img_A7T2MakQ0N090897grScF8HUTxIBxCmwyDVIRJo/edit#)

[Report Card Text translated](https://docs.google.com/document/d/1RgI8GEUQu8McQqcghWkyFnPT2cfBvIz8zKqPP9Ubvy0/edit)

[Translation Errors to Fix in Translated Items](https://docs.google.com/document/d/1buLXZK8kTT2xOXmiAS0dik6VjnvkS13iVZTbE6vx8ak/edit)
