### ISSUE TITLE
Links needed for Report Card

### ISSUE THREAD

**Issue by mraisle** [edgi-govdata-archiving/EEW_Planning#340]

**Comment by mraisle** [comment]
Here are the links that we need to put into the report card (please edit this comment to add them):
- [] The Jupyter notebook link we want folks to use
- [] The Github repo link to making reports (have this one, just need to make sure about settings)
- [] What link "contact us" should go to 
- [] What link "A full list of EEW members, including their roles in this project, can be found here" should go to
- [] The current EEW website link

**Comment by ericnost** [comment]
We actually have two notebooks:
CDs and States - https://colab.research.google.com/github/edgi-govdata-archiving/ECHO-Cross-Program/blob/master/AllPrograms.ipynb
Nationwide - https://colab.research.google.com/github/edgi-govdata-archiving/ECHO-Cross-Program/blob/master/ECHO_National.ipynb
