### ISSUE TITLE
Fill out Communications Planning Form for Spanish Language Report Release

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#347]
https://docs.google.com/document/d/1P74gDbv3dkR-KlXOK7s8em3sBTd8yiMLijGUUJBDalA/edit#heading=h.e48a8odjc1ci

**Comment by lesliealanis** [comment]
here is the comms planning for the Spanish report event: https://docs.google.com/document/d/1h8hNMa3BXb3SmV-W4etoNT7s25uLS_O6rgXJLGw9iCk/edit?usp=sharing 

this issue should remain open until we fill out the "Working Draft of Media Release Package:" section
