### ISSUE TITLE
echo-by-zip.ipynb - Colaboratory

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#35]
┆Issue is synchronized with this [Trello card](https://trello.com/c/TF7bwagq)
┆Attachments: <a href="https://colab.research.google.com/github/edgi-govdata-archiving/ECHO-by-Zip-Code/blob/master/echo-by-zip.ipynb#scrollTo=goH-yyN6Hb3J">https:&#x2F;&#x2F;colab.research.google.com&#x2F;github&#x2F;edgi-govdata-archiving&#x2F;ECHO-by-Zip-Code&#x2F;blob&#x2F;master&#x2F;echo-by-zip.ipynb#scrollTo&#x3D;goH-yyN6Hb3J</a> | <a href="https://trello-attachments.s3.amazonaws.com/5e45be67a561163da1659b54/5e4ef099a7406a7f0d16c1f9/903b2f8a273343f22848006f6fa439a2/colab_favicon_256px.png">colab_favicon_256px.png</a>

**Comment by Frijol** [comment]
@lourdesvera what is the issue/what needs doing here?
