### ISSUE TITLE
Review pollution reports

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#354]
Review pollution reports to figure out possible ways to summarize this data set we haven’t really worked with before, questions that could be asked of it (2 weeks)

**Comment by lourdesvera** [comment]
@Frijol @ericnost do you know what this means?

**Comment by ericnost** [comment]
https://edgi.slack.com/archives/CKN6FMX42/p1612296553003800

lol we probably shouldn't create issues if we don't know what they are?

**Comment by ericnost** [comment]
What can a notebook do or help with in cases other than Greenroots/Chelsea?
- automatically compiling some of the information @emfreeman and @lee-hyun1 have already gathered
- exceedences chart (number of effluent violations and % exceeded by pollutant, coloured according to health risk)
- total permitted levels for Fiscal Year 2020
- separating monitored and regulated and monitored but unregulated pollutants
- doing all this for one or multiple facilities in a watershed
what else? I really think the value-add of a notebook compared to the ECHO interface is aggregating info for multiple facilities to make a cumulative impacts argument, somewhat escaping the narrow logic of permitting.

**Comment by ericnost** [comment]
Example output of a notebook compiling NPDES permit exceedence data and charting it
![image](https://user-images.githubusercontent.com/6888951/110659800-ea3be680-8190-11eb-8b12-9a5ad4c54326.png)
From: https://colab.research.google.com/drive/1Kdc6vzgWywesDI-u9RS8rAdex6tr3y79?usp=sharing#scrollTo=Ylalhm0wbt2p
