### ISSUE TITLE
Brainstorm ideal headline outcomes from project

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#357]
- [x] create a document for headlines
- [ ] set a 30 minute meeting
- [ ] brainstorm

**Comment by lesliealanis** [comment]
I added a couple headlines here: https://docs.google.com/document/d/1Lixyn5_YbBQ-T-ysPlBrn1QTIm5XmKbw36YOqTrZB1g/edit?usp=sharing
