### ISSUE TITLE
Watershed group outreach spreadsheet

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#360]
Make sure spreadsheet is complete with group information. https://docs.google.com/spreadsheets/d/1v1DcgpNxDfM8dqJIRZLgngute61INzz6XC46ANySUi4/edit?usp=drive_web&ouid=110602273190303993217

**Comment by Frijol** [comment]
I think @cullenbober @sonjasteingrims @Fvolz99 and @lizk143 are also working on this!

**Comment by lesliealanis** [comment]
Linked with issues #355 #363 and #391
