### ISSUE TITLE
Hold Github Onboarding

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#362]
- [x] Add folks to the github (@lourdesvera )
- [x]  Schedule
- [x] Gather materials
- [x] hold onboarding

**Comment by Frijol** [comment]
Now scheduled for Friday

**Comment by Frijol** [comment]
duplicate of https://github.com/edgi-govdata-archiving/EEW_Planning/issues/356

**Comment by Frijol** [comment]
Also of https://github.com/edgi-govdata-archiving/EEW_Planning/issues/343. Have closed both those other issues to let this be the canonical issue.
