### ISSUE TITLE
Investigate which watershed groups cover EJ areas

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#363]
- [x] download watershed shapefile (get from @ericnost ?) OR eyeball and see if there are facilities in EJ areas next to the water)
- [x] upload to EJ screen
- [x] grab [watershed group sheet](https://docs.google.com/spreadsheets/d/1v1DcgpNxDfM8dqJIRZLgngute61INzz6XC46ANySUi4/edit#gid=0)
- [x]  note where the watershed groups are located and the EJ indices in those locations

(use https://ejscreen.epa.gov/mapper/)

**Comment by ericnost** [comment]
Sorry I missed this earlier. Not sure what I can add other than to say that you can add watersheds in EJScreen. Go to Add Maps -> Additional Layers -> Water Features. And then in the legend select HUC 12. That's a different size HUC than what we have been working with, but I don't think it really matters. I don't think you can see facilities in EJScreen, but I think we can just assume there are facilities everywhere (and especially in the EJScreen-identified EJ areas....) Which is just to say, one way to approach it is, use EJScreen to look at EJ indices, note the watershed of specific EJ areas, and then see if there is a watershed group?
