### ISSUE TITLE
Github onboarding learnings

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#365]
This is an issue for the Github Onboarding workshop. Please add a comment with either:

* Something you learned
* Something you'd like to know more about

**Comment by emfreeman** [comment]
How to look at Milestones

**Comment by Annie-Ma-3399** [comment]
- Learned: How to add labels and projects
- Learn more about: Milestones

**Comment by lee-hyun1** [comment]
I'd like to learn more about how to share code on GitHub

**Comment by lizk143** [comment]
moving issues from to do to in progress and so on

**Comment by Fvolz99** [comment]
Learned some of the basics of using Github

**Comment by cullenbober** [comment]
Learned how the EDGI/EEW project management and tracking process works on GitHub

**Comment by saraannwylie** [comment]
I didn't realizing closing the issue automatically moved it to done!

**Comment by phil-webb** [comment]
How to form issues with the appropriate tags
