### ISSUE TITLE
Draft press release

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#372]
https://docs.google.com/document/d/1P74gDbv3dkR-KlXOK7s8em3sBTd8yiMLijGUUJBDalA/edit#heading=h.e48a8odjc1ci

**Comment by lesliealanis** [comment]
here is an outline of the watershed project press release: https://docs.google.com/document/d/1qW5aX8wOes0WJ_2p8pRaHDs0JRcUXHKbdfnG80vySIg/edit?usp=sharing
