### ISSUE TITLE
schedule a mindfulness activity together

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#373]
https://conferences.bham.ac.uk/blog/10-wellbeing-activities-for-conferences/

https://blog.neolms.com/9-easy-mindfulness-activities-for-the-virtual-classroom/

**Comment by lourdesvera** [comment]
https://www.mtdtraining.com/blog/25-virtual-meeting-ice-breaker-ideas-activities.htm

**Comment by lesliealanis** [comment]
I made this mural of a gratitude exercise we could use (it needs a more creative name): https://app.mural.co/t/edgi7967/m/edgi7967/1615952893149/e25c6b68b610adb7c89f04a2fb968ebe3939762d
