### ISSUE TITLE
ECHO Watch Proposal

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#38]
┆Issue is synchronized with this [Trello card](https://trello.com/c/ZYZ8EF3S)
┆Attachments: <a href="https://docs.google.com/document/d/1pko4WTxj0L2LzjchuS3Tf28ybBp4IxqRUY-mNvwT3Os/edit?usp=drive_web">ECHO Watch Proposal</a>

**Comment by Frijol** [comment]
@lourdesvera what needs to be done here/what is the issue?

**Comment by lourdesvera** [comment]
proposal for funding- done
