### ISSUE TITLE
Think about submitting to Cascadia R Conf

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#390]
CFP: https://cascadiarconf.com/speakers/

Priority to folks in the Cascadia region but others accepted

Due by March 15th

**Comment by Frijol** [comment]
cc @mraisle this is due in ~2 weeks, any ideas for good R stuff we might submit to this?

**Comment by mraisle** [comment]
hey @Frijol - I read the description and don't have to much to add but I think if you submit something probably the first bullet "Using R for collaborating and communicating with a diverse audience: using blogs/websites, reports, Shiny Dashboards, leaflet maps" would fit best with that we have done. And/or the comment about our use of packages - specifically the pagedown package was critical for our production of html and pdf reports.

**Comment by Frijol** [comment]
cc @lourdesvera  is this something you're interested in pursuing at all? I don't know that I'll be around during conference time. It's ok if we want to just drop this idea, too

**Comment by Frijol** [comment]
@lee-hyun1 also wondering if this is something you might be excited to submit a proposal to around your analysis of Chelsea Creek? Typically they'd expect a paragraph or so about what you'd expect to present at the application stage, the talk would be early June if accepted. I think it would be really cool if you could show how you've used R to investigate environmental justice concerns

**Comment by lee-hyun1** [comment]
@Frijol It sounds interesting, but I'm not sure if what I've done so far warrants a presentation...

**Comment by Frijol** [comment]
Fair, but if you plan to continue using R for this investigation, that's fair game! I know a lot of tech-talk givers who subscribe to a "talk-driven development" model; it's very common to apply for this type of conference before the work itself is complete or even fully fleshed out.

**Comment by lee-hyun1** [comment]
Title and abstract draft for the Cascadia R Conference 2021 talk submission: https://docs.google.com/document/d/17x5whywGSFIKX60pVbnMIVfSC9j4XyItIu8-2whzSkM/edit

@Frijol Sorry for the late notice, but could you please review my abstract for the Cascadia conf? It is due tomorrow so if you could look over it by then that'd be great

**Comment by lourdesvera** [comment]
@Frijol @lee-hyun1 should I close this issue?

**Comment by lee-hyun1** [comment]
@lourdesvera you can close it. The deadline was moved to 3/22 so I've just been editing it a bit but I'm almost done

**Comment by lee-hyun1** [comment]
Application submitted on 3/21
