### ISSUE TITLE
Schedule a meeting to discuss accessibility options for upcoming events

### ISSUE THREAD

**Issue by lesliealanis** [edgi-govdata-archiving/EEW_Planning#392]
accessibility options: https://docs.google.com/spreadsheets/d/1C-Yfk8U8MET-BNpmTTkRIsAsPPdfrTmwKQj3e6PSC3Q/edit#gid=1227503524

**Comment by lesliealanis** [comment]
Perhaps Friday or next week would be a good time to meet

**Comment by Frijol** [comment]
Happy to join, want to send around a when2meet? Or, Fridays other than 10:30-11:30PT work for me

**Comment by Frijol** [comment]
Might be helpful: https://docs.google.com/document/d/1_WHzHnaNOUr7VNAKc2X_61PJsuf7dp65tWaB2hzLBYA/edit

**Comment by lesliealanis** [comment]
Yes, I made one here, I can share it in eew coordination: https://www.when2meet.com/?11276489-yxpsj
