### ISSUE TITLE
Revise Code of Conduct

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#393]
Leslie is leading this initiative (@lesliealanis can you drop links to the resources you've been collecting?)

**Comment by Frijol** [comment]
Adding this nice little typeform mini-CoC csv,conf uses as part of the application to speak:

**Comment by Frijol** [comment]
Kelsey/Leslie working on this, hoping to have a complete draft by next Monday

Notes: https://docs.google.com/document/d/1c5Mxg_ybyLtWdAxPrjP37q5YnDgKjMn4s6lve2EshiQ/edit#

Draft: https://docs.google.com/document/d/1zqFPVjQ__x3tfcSlir-jeO7O-mcCh4oKyNNlJEpJMOU/edit#

**Comment by lesliealanis** [comment]
Here is the mural we worked on during the open coordination meeting: https://app.mural.co/t/edgi7967/m/edgi7967/1611251708200/c8401cad5c931567bfaaad9d35aa7c03642d3c98 

And the links to other codes of conduct: 
https://geekfeminism.wikia.org/wiki/Code_of_conduct_evaluations

https://indieweb.org/code-of-conduct-examples

**Comment by Frijol** [comment]
From CS&S page, another thing to check against on Monday:

Events must have a code of conduct, or concrete plans for creating one, that includes:
Clear guidelines for reporting
Clear language about how to file reports
A review and appeal process
A transparency report
Enforcement processes, or concrete plans for creating them.

**Comment by Frijol** [comment]
yay approved! https://docs.google.com/document/d/1zqFPVjQ__x3tfcSlir-jeO7O-mcCh4oKyNNlJEpJMOU/edit#
