### ISSUE TITLE
Chelsea Creek Permit Comparison

### ISSUE THREAD

**Issue by emfreeman** [edgi-govdata-archiving/EEW_Planning#394]
Permit comparison project.

**Comment by emfreeman** [comment]
Compiling data from the **unregulated but monitored** pollutants via the effluent charts from ECHO. All work can be found within the folder linked [here](https://drive.google.com/drive/folders/1u_gwCo7dLmK2CVZtfmm65jnuSvtJgrHy?usp=sharing).

**Comment by lizk143** [comment]
Working on our permit contrasts. The excel sheet is now moved into the permit folder.

**Comment by Frijol** [comment]
Splitting this out into many issues, trackable on this project board: https://github.com/edgi-govdata-archiving/EEW_Planning/projects/18

Feel free to keep using this issue if useful, or close it if the new tooling works better for you
