### ISSUE TITLE
archive or delete CD repo

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/EEW_Planning#395]
https://github.com/edgi-govdata-archiving/CD

We created this at the very beginning of the Democratizing Data report but it never got used.

It is a private repo that I don't have access to. I am wondering if @Frijol does?

**Comment by Frijol** [comment]
I do! Preference between archive vs delete?

**Comment by ericnost** [comment]
I think this should be delete as there's nothing actually in the repo, I think
