### ISSUE TITLE
E-Mail Templates for Potential Partners

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#42]
┆Issue is synchronized with this [Trello card](https://trello.com/c/zMbbxtH7)

**Comment by Frijol** [comment]
@lourdesvera what needs to be done here/what is the issue?

**Comment by lourdesvera** [comment]
We need to create e-mail templates that direct potential event partners or people interested in the event to the landing page.

**Comment by lourdesvera** [comment]
Who would like to claim this?

**Comment by crgreenleaf** [comment]
We can do this in MailChimp to make it look super professional. @lourdesvera Let me know and we can tag team that

**Comment by Frijol** [comment]
@crgreenleaf I feel like I saw you working on this recently, is that accurate? I'm combing through issues & want to make sure we don't have duplicates & abandoned issues

**Comment by Frijol** [comment]
related: https://github.com/edgi-govdata-archiving/EEW_Planning/issues/45

**Comment by crgreenleaf** [comment]
@Frijol  This is now linked with #182 so we can close this!
