### ISSUE TITLE
Planning Doc

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#44]
┆Issue is synchronized with this [Trello card](https://trello.com/c/BbqALVti)
┆Attachments: <a href="https://docs.google.com/document/d/1rykQF5tSXKgT1Vy8otCbJcjFZeN22oozKkcdxbOcnvk/edit?usp=drive_web">ECHO Hackathon Planning Doc</a>

**Comment by Frijol** [comment]
@lourdesvera what is the issue/what needs doing here?

**Comment by lourdesvera** [comment]
We made the planning doc. Closing this issue.
