### ISSUE TITLE
(Potential) Partnerships

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#45]
Fill out our partner info as we connect with them

┆Issue is synchronized with this [Trello card](https://trello.com/c/uBnZAvZD)

**Comment by Frijol** [comment]
@lourdesvera are there more details here? Is there an associated doc and/or list of partners?

**Comment by lourdesvera** [comment]
We need to create a spreadsheet with a list of partners and their contact information. @saraannwylie who do you think should be responsible for this?

**Comment by Frijol** [comment]
@crgreenleaf should this issue be assigned to you?
