### ISSUE TITLE
Create slideshow for Stonybrook event

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#5]
┆Issue is synchronized with this [Trello card](https://trello.com/c/EGFiAHSh)

**Comment by saraannwylie** [comment]
Here's [the presentation](https://docs.google.com/presentation/d/14HrFGziF-C_hO9Ar9WwR8WAdblf6cHf0ZPtKKxcN-jQ/edit#slide=id.g739a273cc8_0_5)
