### ISSUE TITLE
Project Description Slides

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#52]
Whoa! Look! It's a checklist—you can create tasks, tag your teammates, and check-off tasks as you go and achieve milestones.

┆Issue is synchronized with this [Trello card](https://trello.com/c/ftXD9dlM)

**Comment by Frijol** [comment]
@lourdesvera the issue description doesn't seem to match the issue title. What needs doing?

**Comment by lourdesvera** [comment]
Weird, it got messed up with the trello. These are the slides to describe each track. We did them for the Stonybrook event. Closing this issue.
