### ISSUE TITLE
Add sign-up slide

### ISSUE THREAD

**Issue by calderEDJ** [edgi-govdata-archiving/EEW_Planning#53]
Add sign-up slide to slide deck and figure out who will be putting people into breakout rooms

┆Issue is synchronized with this [Trello card](https://trello.com/c/AFtUuIhF)

**Comment by Frijol** [comment]
@calderEDJ is this still relevant, or was it for the Stonybrook event?

**Comment by calderEDJ** [comment]
it was just for stonybrook. I'll close the issue
