### ISSUE TITLE
Add navigational headers for each primer doc

### ISSUE THREAD

**Issue by calderEDJ** [edgi-govdata-archiving/EEW_Planning#54]
┆Issue is synchronized with this [Trello card](https://trello.com/c/YGZoKbt0)

**Comment by ericnost** [comment]
added a draft of what this could look like here: 

https://docs.google.com/document/d/15YLFX4-281IsexBGJrnBiCSBnIR5vX_F_BnRs-9hSSE/edit#

**Comment by lourdesvera** [comment]
I think that's good. Closing this issue.
