### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by calderEDJ** [edgi-govdata-archiving/EEW_Planning#55]
need naming convention for each new doc in the tracks

┆Issue is synchronized with this [Trello card](https://trello.com/c/hYqLmPFj)

**Comment by Frijol** [comment]
@calderEDJ @lourdesvera where would be an appropriate place to document naming conventions? Somewhere in this repo, or in a doc?

**Comment by lourdesvera** [comment]
In a doc but copied to the Repo? We should have naming conventions for every file that might be saved throughout the course of the event? Jupyter notebooks, CSVs, slides, etc. 

Maybe each question in the tracking sheet can have a code or number associated with it and all the documents related to that question will have the code in the file name.

**Comment by lourdesvera** [comment]
I need help with this 

https://docs.google.com/document/d/1EpQTORiuFbbudv9MJHjIghkaAdD8zHy2kHFewswhF3M/edit#

**Comment by lourdesvera** [comment]
@Frijol can you review?

**Comment by Frijol** [comment]
Yep, taking a look!

**Comment by Frijol** [comment]
Commented, back to you!
