### ISSUE TITLE
Fix google drive permissions

### ISSUE THREAD

**Issue by calderEDJ** [edgi-govdata-archiving/EEW_Planning#57]
Fix google drive permissions for public folders

┆Issue is synchronized with this [Trello card](https://trello.com/c/glpjDaHz)

**Comment by Frijol** [comment]
@calderEDJ can you be more specific? What needs fixing?

**Comment by lourdesvera** [comment]
We need to make sure all the folders in the google drive are available for anybody to edit with the link

**Comment by lourdesvera** [comment]
@calderEDJ how are you doing with this?

**Comment by calderEDJ** [comment]
I think this is done.
