### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by calderEDJ** [edgi-govdata-archiving/EEW_Planning#58]
come up with naming conventions for notebooks and apply them

┆Issue is synchronized with this [Trello card](https://trello.com/c/FOcQwQOC)

**Comment by Frijol** [comment]
Is this separate from https://github.com/edgi-govdata-archiving/EEW_Planning/issues/55?

**Comment by Frijol** [comment]
closing as it seems to be a duplicate of https://github.com/edgi-govdata-archiving/EEW_Planning/issues/55
