### ISSUE TITLE
Create landing page version of website

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#6]
Prototyped on Mural https://app.mural.co/t/echoevents4112/m/echoevents4112/1584647071595/060d6b09b0d0f362c72588aada5d9de0cc99fda7

┆Issue is synchronized with this [Trello card](https://trello.com/c/hxFLCr3C)

**Comment by Frijol** [comment]
Let me know if you want to work with somebody on this, I know I'd want to bounce ideas off of somebody if I were doing it

**Comment by Frijol** [comment]
Now that the logo is up, is this site public? Is it ok to send people the link?

**Comment by Frijol** [comment]
some notes I had on this concept from a while ago:

# ECHO Watch Website: iterative approach

Philosophy here is this:
![](https://miro.medium.com/max/828/1*qINsG4WH_BDN-viMJUH6Ng.png)
 
It doesn't have to be everything all at once; let's start with the most basic useful thing we can think of & build from there.

## 1. Landing page

Good for:
* People who might be interested to hear about the event for the first time
* For EDGI: getting something made really quickly and cheaply
* For EDGI: marketing/collecting interest with a first pass at external messaging
* For reporters, potential hosts: something concrete we can point people to

Spec:
* No logins for users
* Use a pre-built form from Mailchimp to collect emails
* Editing the site is more or less just editing text (it doesn't really have anything fancier than that)

Looks kinda like:

![](https://startbootstrap.com/assets/img/screenshots/themes/landing-page.png)

* Takes about an hour to build (even if you don't code)
* We can start promoting the events immediately
* Call to action: probably collects email addresses & locations of people interested so we can send out a blast when there are more specific calls to action (attend/host an event)
* Don't have to have our whole story straight, we're just collecting interest

Something like

> *We're working on an event series to help people find out more about emissions and enforcement in their local areas.*
> 
> **Interested? Sign up here and we'll let you know when we're getting started! [sign up box]**
> 
> A little bit of detail (just a few sentences) like "EDGI's report X showed EPA enforcement decline. We want people to be able to see for themselves through interactive analysis of enforcement & compliance in their areas. Email XYZ if you'd like to get involved in hosting!"

Here is a bit more on [landing pages](https://unbounce.com/landing-page-articles/what-is-a-landing-page/)

Tech-wise, this is simple enough that we could build it in Wordpress, or in code, and then completely go another direction in the future (not a big loss)

## 2. Website that supports events

Good for:
* For coordinators: listing upcoming events
* For EDGI: still a pretty easy developer lift, we could handle this internally in Wordpress
* For attendees: finding events and deciding whether to go
* For attendees at events: helping people understand the different tracks (includes links to tutorials)

Spec:
* Still mostly static, no user logins
* Might use a Google Sheet as a backend (e.g. hosts fill out a Google Form which then auto-populates a map on the site) – or this could be done manually since we probably have low volume. This should all be doable by a non-programmer
* Probably a couple of pages:
  * The original landing page (might now become the homepage – same main call to action, maybe more info)
  * About us
  * Logistics page with different events & info
  * Page of tutorials
  
## 3. Website that includes output
Good for:
* People at events trying to figure out what needs working on
* Reporters to see outputs
* EDGI to have output in one, organized place

Spec:
* Begins to be a bit challenging – how do we want people to contribute their outputs, where do we want that saved, how do we want it organized?
* This is the sort of detail we need to figure out, but it doesn't have to bog down parts 1 and 2

**Comment by Frijol** [comment]
cc @EDGI-Comms

**Comment by lourdesvera** [comment]
We need to do final edits to landing page copy by pasting it into a google doc, editing, commenting with questions, and have people review by Thursday's meeting @calderEDJ 

Edit the text on the landing page to reflect the descriptions of our tracks and the goals of the events. We should tone down the language a little bit but still highlight how we are responding to white supremacy-caused environmental injustice.

**Comment by lourdesvera** [comment]
We also need to add the logo.

**Comment by Frijol** [comment]
I think we need to remove links to pages we're not using (obvious blank or template text) in order to go live

**Comment by lourdesvera** [comment]
@EDGI-Comms @calderEDJ how is the About and Partners copy going?

**Comment by lourdesvera** [comment]
@calderEDJ how is this going? Do you want to have a work session on this Thursday morning?

**Comment by calderEDJ** [comment]
hey, sorry I missed this. I'm free now if you are

**Comment by lourdesvera** [comment]
@calderEDJ Sorry if I dropped off, what's holding us back on this?

**Comment by lourdesvera** [comment]
@Frijol @crgreenleaf Can you review this landing page so we can get the go-ahead to send it to folks?

**Comment by crgreenleaf** [comment]
I have some small comments!

- there is a typo space at the end of the first sentence (_"We want clean air..."_)
- For the following text, Could this be its own box? I think the description of "Environmental Enforcement Watch" should be its own thing: _"We want clean air, clean water, and an end to environmental racism and injustice . Strong environmental regulation is important, but it’s only as good as its enforcement. According to former Assistant Administrator of EPA’s Office of Enforcement and Compliance Assurance, Cynthia Giles: “Significant violations occur at 25% or more of facilities in nearly all programs for which there is compliance data. For many programs with the biggest impact on health… Significant violation rates of 50% to 70% are not unusual. These widespread violations have a direct effect on people’s health”. (Harvard Law School)""_

What else needs to happen before this is live?

**Comment by lourdesvera** [comment]
What needs to be done to circulate vs. what needs to be done to be a full landing page.

Funders - NULab, EDGI, Packard (?) Doris Duke (?)
Partners - need a conversation with Sunrise, Stonybrook folks

**Comment by lourdesvera** [comment]
@ericnost can you ask stonybrook folks if they'd like to be listed on the partners part of "about"?
@crgreenleaf can you ask sunrise if they'd be okay being listed?

**Comment by lourdesvera** [comment]
Closing this issue and transitioning it to #213
