### ISSUE TITLE
Notes document for each track

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#60]
┆Issue is synchronized with this [Trello card](https://trello.com/c/UNhGOClJ)

**Comment by Frijol** [comment]
Suggestions for notes sections:

* Any sections that surprised you
* Anything that was confusing– what questions do you have about the information in the report? Incl. terms that need more explanation
* What questions do you wish the Notebook answered?

**Comment by saraannwylie** [comment]
Notes documents for each track are [in this folder](https://drive.google.com/drive/folders/1-nomDJZu7GCGv3WWQkuypdgk9zvsjXBe?usp=sharing) and linked in the [sign in sheet](https://docs.google.com/document/d/1XR2_7f6aO-NqAvlVuXCw9iBkrcgiMKevl5AIE5ed9ds/edit#) and [congressional district primer](https://docs.google.com/document/d/17fBEiAVdTJvPmO7ZRC86vfGKkfHMVMHkQnyMJOHqMjw/edit)
