### ISSUE TITLE
Add Jupyter instructions to the top of each Notebook

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#61]
Pulls some of the instructions from the [Jupyter Notebook primer](https://docs.google.com/document/d/1fAWoUbsISSV-tFZvASbTDE6KRl6Hkeu4p-N2jpQFmt0/edit#heading=h.n6h5st5yipeh) directly into the Notebooks. @lourdesvera has a prototype of this locally, I can go ahead and apply it to all of the notebooks today once she shares it

* [x] [Hazardous Waste](https://github.com/edgi-govdata-archiving/ECHO-Hazardous-Waste)
* [x] [Air](https://github.com/edgi-govdata-archiving/ECHO-Air-Violations)
* [x] [Water](https://github.com/edgi-govdata-archiving/ECHO-CWA-Compliance)

┆Issue is synchronized with this [Trello card](https://trello.com/c/4Vr64BV4)

**Comment by Frijol** [comment]
Oh it's here! I can work with this https://colab.research.google.com/drive/1iEQZaEYBZD1ji6K7ZXNNRLrPAPmAaiMb

**Comment by Frijol** [comment]
Heads up I made an image assets repo bc the Google Drive image links were not loading for me https://github.com/edgi-govdata-archiving/EEW-Image-Assets/

**Comment by ericnost** [comment]
I can do this for Water, with a pull request, since I was also assigned the task of adding more context to the enforcement and inspection notebooks

**Comment by Frijol** [comment]
I'm working on the RCRA ones

**Comment by Frijol** [comment]
drafted in https://github.com/edgi-govdata-archiving/ECHO-Hazardous-Waste/pull/2

**Comment by ericnost** [comment]
Relevant here: should we clear output before syncing with Colab? On one hand, the example output shows participants what kind of results they should get. OTOH, I find it clutters the notebook and can lead to confusion (did I run this already)?

**Comment by Frijol** [comment]
Yeah, I was discussing briefly w/ @shansen5 and I think we landed on Cell > All Output > Clear before committing

**Comment by Frijol** [comment]
might be a good idea to develop some contribution guidelines we can ref across all the notebook repos!

**Comment by Frijol** [comment]
Starting on Air as well

**Comment by Frijol** [comment]
cc @shansen5

**Comment by Frijol** [comment]
I think we got them all!
