### ISSUE TITLE
Step by step for breakout sessions

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#62]
Where will this list go?

List of different breakout rooms?

┆Issue is synchronized with this [Trello card](https://trello.com/c/Q4MlKoM4)

**Comment by Frijol** [comment]
Is this the same as making a primer for moderators? Or do we need a separate issue for that?

**Comment by saraannwylie** [comment]
It's covered in the steps of each note document for each breakout room
