### ISSUE TITLE
create demo for Jupyter Notebooks

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/EEW_Planning#67]
create a video demo on the basics of using a Jupyter Notebook that can be referenced by participants as they use the notebook (alongside the How To at the top of each nb)

┆Issue is synchronized with this [Trello card](https://trello.com/c/jwRyMMSO)

**Comment by crgreenleaf** [comment]
I added a screen grab video demo of the congressional report into the promo video #194

**Comment by Frijol** [comment]
would this be a good thing for @maalvikabhat to do?

**Comment by ericnost** [comment]
I think we should go through the validation process first #203, but yes!

**Comment by maalvikabhat** [comment]
I can do this next week then?

**Comment by ericnost** [comment]
Yea, let's do it after we review/validate the notebook, which may require changes that should be reflected in a demo...

**Comment by crgreenleaf** [comment]
Has this been done?

**Comment by maalvikabhat** [comment]
Put the link for this in https://docs.google.com/spreadsheets/d/1Z2rBoGqb_SXW6oAu12A6TCWEJGV1pk0YxL13P_Z5Wlw/edit#gid=903191621 this spreadsheet!
