### ISSUE TITLE
Organize meeting on audience/stakeholders

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#69]
┆Issue is synchronized with this [Trello card](https://trello.com/c/fenEna9m)

**Comment by Frijol** [comment]
@calderEDJ @crgreenleaf are one of you organizing this? Or should I for next Tuesday's meeting?

**Comment by lourdesvera** [comment]
➤ crgreenleaf commented:

lourdes467 @ calderEDJ kelseybreseman1 Next Tuesday works for me?

**Comment by Frijol** [comment]
drafted a meeting agenda here, lmk if this seems reasonable to you! https://docs.google.com/document/d/1ZraEefQMhF1XWDrZi8Igr9gQUWD2n2LM5n26CLmxbB8/edit#heading=h.gjb62my7cszh

**Comment by Frijol** [comment]
We did this a while ago! Closing
