### ISSUE TITLE
Create full website for public events

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#7]
* [x] create front page
* [x] create template for other pages
* [x] post event calendar
* [x] create sub pages
* [x] Collect, edit, and write website copy 
* [x] feedback meeting about website
* [x] website committee meeting/training on how to manage website

---

Should be drafted at https://www.environmentalenforcementwatch.org/

This Issue should most likely be broken out into several smaller issues.

Original spec doc for website: https://docs.google.com/document/d/1-kFYteHqb4Xj6kcHpXSBka-XIxfJbmvIdnF8TTaEHEI/edit

┆Issue is synchronized with this [Trello card](https://trello.com/c/MxsFp6kI)

**Comment by Frijol** [comment]
Low priority until after we have a finished public landing page https://github.com/edgi-govdata-archiving/EEW_Planning/issues/6

**Comment by Frijol** [comment]
cc @EDGI-Comms

**Comment by lourdesvera** [comment]
I created the front page and it needs to be reviewed.

**Comment by lourdesvera** [comment]
* [ ] create front page
* [ ] create template for other pages
* [ ] post event calendar
* [ ] create sub pages
* [ ] Collect, edit, and write website copy

**Comment by Frijol** [comment]
@lourdesvera I copied your checklist up into the issue description because then we get a progress bar for it when we're on the Issues page

**Comment by lourdesvera** [comment]
Meeting for this on 5/29 at 12pm EST

**Comment by lourdesvera** [comment]
This is more of a milestone now. I'm going to split the checklist into issues and set this as a goal for the end of the month.

**Comment by lourdesvera** [comment]
Aiming to get this done by June 30th.

**Comment by Frijol** [comment]
@ozzmotic adding you to this issue in case helpful, not sure how relevant the checklist still is
