### ISSUE TITLE
Finish EEW Planning repo readme

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#71]
┆Issue is synchronized with this [Trello card](https://trello.com/c/qPdCBwDh)

**Comment by Frijol** [comment]
@lourdesvera what's needed here? Should the [tracking spreadsheet](https://docs.google.com/spreadsheets/d/1Z2rBoGqb_SXW6oAu12A6TCWEJGV1pk0YxL13P_Z5Wlw/edit#gid=1601968109) be linked?

**Comment by lourdesvera** [comment]
@Frijol Yeah, let's link the tracking spreadsheet and planning doc?

**Comment by lourdesvera** [comment]
Added links to planning doc and EEW tracker
