### ISSUE TITLE
Cole/Casey work through Github 101

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#72]
Here are the slides! https://docs.google.com/presentation/d/1UsPFtVVGwu8hdp5E-eWEgMhfMigpZ2qpNCkKTdxpeVE/edit We got up to Slide 29

┆Issue is synchronized with this [Trello card](https://trello.com/c/YYRaR9IN)

**Comment by calderEDJ** [comment]
Thanks, Kelsey, I'll try to find a time this week that works for Casey and I to review this
