### ISSUE TITLE
Edit landing page copy

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#8]
Edit the text on the landing page to reflect the descriptions of our tracks and the goals of the events. We should tone down the language a little bit but still highlight how we are responding to white supremacy-caused environmental injustice.

┆Issue is synchronized with this [Trello card](https://trello.com/c/bC3o3dhH)

**Comment by Frijol** [comment]
Is this a sub-task of https://github.com/edgi-govdata-archiving/EEW_Planning/issues/6 ?

**Comment by lourdesvera** [comment]
> Is this a sub-task of #6 ?

Yes, I'll close this issue and consolidate
