### ISSUE TITLE
Create place in public GDrive folder to store CSV files and Jupyter notebook files

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#80]
Create general folders in environmental_enforcement_watch_public to store Jupiter notebooks and CSV outputs.

The major questions to address are:
1. What will the filename conventions be?
2. Will these jupyter notebooks, CSV outputs, related slides, research docs, and other outcomes be together in the same folder? Or should we have one folder for jupyter notebooks, another for CSV data, other for slides, etc. 

Afterwards:
1. Link to these places in primers and how-tos

┆Issue is synchronized with this [Trello card](https://trello.com/c/LzjIBVFF)

**Comment by Frijol** [comment]
held up by https://github.com/edgi-govdata-archiving/EEW_Planning/issues/55, which is currently in review
