### ISSUE TITLE
Congressional Report Card

### ISSUE THREAD

**Issue by crgreenleaf** [edgi-govdata-archiving/EEW_Planning#84]
https://www.canva.com/design/DAD61oZJP6o/0jJtyWCF0SnLaAxrB_QKyw/edit

┆Issue is synchronized with this [Trello card](https://trello.com/c/ykpXslcb)

**Comment by lourdesvera** [comment]
How's this going @crgreenleaf ?

**Comment by lourdesvera** [comment]
@crgreenleaf what should the timeline for this be?

**Comment by lourdesvera** [comment]
@calderEDJ is this done?

**Comment by lourdesvera** [comment]
Archiving this issue because other issues have taken its place
