### ISSUE TITLE
Data Visualization Experiments

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#85]
Create a data visualization from ECHO data. Be creative!

┆Issue is synchronized with this [Trello card](https://trello.com/c/jiN09XJx)

**Comment by calderEDJ** [comment]
https://www.canva.com/design/DAD8DeOt_ds/7JttmhvLBLUGzhQbK8HMXA/view?utm_content=DAD8DeOt_ds&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by saraannwylie** [comment]
Here is my idea: [](https://drive.google.com/file/d/1KgSwEjHh48HVNP5q9sskPf_AttvzTxKS/view?usp=sharing)

**Comment by lourdesvera** [comment]
![image](https://user-images.githubusercontent.com/23300449/81972298-622c9500-95f0-11ea-8509-f36c5a26faa7.png)

**Comment by crgreenleaf** [comment]
https://www.canva.com/design/DAD61oZJP6o/share/preview?token=sRVgLq3DEGOHtSjjMAAr7g&role=EDITOR&utm_content=DAD61oZJP6o&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by ericnost** [comment]
notebook for summarizing and mapping non-compliance: https://www.youtube.com/watch?v=mGdYyj0BVyw (lives on my computer right now, updated to include watershed-level data)

interactive map to show facilities near areas of interest: https://www.youtube.com/watch?v=t8gdRIk1Alo (lives on my computer right now, updated to include watersheds)

another interactive map summarizing and mapping non-compliance: https://www.youtube.com/watch?v=6gWLiK8cIs0 (lives on my computer right now)

**Comment by Frijol** [comment]
Simple but effective:
![Screen Shot 2020-05-14 at 11 39 15 AM](https://user-images.githubusercontent.com/454690/81972555-9fd0f400-95d7-11ea-98d5-a2f477211625.png)
![Screen Shot 2020-05-14 at 11 39 02 AM](https://user-images.githubusercontent.com/454690/81972556-a0698a80-95d7-11ea-858f-88d43914231f.png)

A little more detailed:
![Screen Shot 2020-05-14 at 11 38 53 AM](https://user-images.githubusercontent.com/454690/81972552-9e9fc700-95d7-11ea-9b28-b0d6966a920b.png)

Needs more interpretation, would like to add lines e.g. "avg household use" to make sensible to ordinary people:
![Screen Shot 2020-05-14 at 11 39 38 AM](https://user-images.githubusercontent.com/454690/81972554-9f385d80-95d7-11ea-8ace-b13cd03c4b2b.png)

**Comment by lourdesvera** [comment]
Cool experiments!
