### ISSUE TITLE
Canva subscriptions

### ISSUE THREAD

**Issue by calderEDJ** [edgi-govdata-archiving/EEW_Planning#87]
Look into the various options for Canva team/individual account pricing. Ideally we could have a few accounts/usernames for event attendees to use for data visualization and report making.

┆Issue is synchronized with this [Trello card](https://trello.com/c/fqmup3rw)

**Comment by calderEDJ** [comment]
So, canva has a teams option and it's $12.95 a month per team member. I guess that would be financially feasible but it's not a very good platform for real-time collaboration; only one person can work on a project at a time. @lourdesvera @saraannwylie @crgreenleaf what are your thoughts on this? If we had like 3-5 accounts to use at an event, we could have break-out rooms at an event with one person editing the canva report and screen sharing while others give input? And then after the event I could synthesize everything into one report?

**Comment by crgreenleaf** [comment]
I know you can make teams and collaborate that way in Canva. I wonder if we have premium whether that would allow us to add people to our team for the data viz breakout just by sending an email. Alternatively, we could design the breakout to have a "master visualizer" that screenshares? That could be frustrating for participants I suppose...

**Comment by crgreenleaf** [comment]
There is also a canva for nonprofits (free!) that we could apply for. https://support.canva.com/account-basics/nonprofit-program/apply-for-nonprofit/

**Comment by saraannwylie** [comment]
that seems like the right call! @crgreenleaf, I am somewhat concerned that through EEW lots of non-profits might use the account to create reports?

**Comment by Frijol** [comment]
Did we apply for free Canva for nonprofits?
