### ISSUE TITLE
Create an onboarding flow for new hires

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#89]
Let's make sure we have an explicit process for orienting each new hire to EDGI, EEW, resources, and their role.

Likely starts with materials from the [EDGI onboarding folder](https://drive.google.com/drive/folders/0B2riIxpG2GHEeWFPSjRMcHJ4NFk)

┆Issue is synchronized with this [Trello card](https://trello.com/c/irGnqsRA)

**Comment by Frijol** [comment]
https://github.com/edgi-govdata-archiving/EEW_Planning/issues/93 should be part of this

**Comment by Frijol** [comment]
Use this video as part of onboarding? Covers intros w key people + hits all the big points about what we're doing and how https://youtu.be/CiNQzwBsFgs

**Comment by Frijol** [comment]
Include current annual report as a doc they can review?

**Comment by Frijol** [comment]
Should also include a set of EEW-specific docs to review, such as naming conventions (https://github.com/edgi-govdata-archiving/EEW_Planning/issues/55)

**Comment by lourdesvera** [comment]
@Frijol can you review this onboarding doc and add any additional resources you think they would need? We also need to go through and add links.

https://docs.google.com/document/d/1ZAdmFXdK4K4VA4s7bkuPPksDJBedlGr4tDrMTZ8xch0/edit#

**Comment by lourdesvera** [comment]
slide 17 has a great list of tasks: https://docs.google.com/presentation/d/1hYUa9-09a4VlG2gEtXguSsry8Z82xQy5nwLCoi0cclA/edit#slide=id.g85c9bd05a9_1_50 combined with the mural.ly: https://app.mural.co/t/edgi7967/m/edgi7967/1591799004480/3f15dc80d1a6c210cdf5126d5a94ce0dca9b3540

**Comment by Frijol** [comment]
took a look at the doc and added suggestions!

**Comment by lourdesvera** [comment]
> Use this video as part of onboarding? Covers intros w key people + hits all the big points about what we're doing and how https://youtu.be/CiNQzwBsFgs

@Frijol @saraannwylie Did we decide on this?

**Comment by lourdesvera** [comment]
> Include current annual report as a doc they can review?

This might be a good idea too?

**Comment by Frijol** [comment]
I think we've hit the advice process stage, go ahead with whatever you think is a good idea?

**Comment by saraannwylie** [comment]
I put the link to the above video into the onboarding doc. https://youtu.be/CiNQzwBsFgs
