### ISSUE TITLE
Add people to GitHub

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#9]
Make sure that everyone involved in EEW planning is on GitHub and using the project board.

┆Issue is synchronized with this [Trello card](https://trello.com/c/1rFJ8GgC)

**Comment by Frijol** [comment]
Is this resolved, or is there more we can do here? Do we need a workshop session on using the tool?

**Comment by Frijol** [comment]
I believe this is done and I gave a tutorial [Github 101](https://docs.google.com/presentation/d/1UsPFtVVGwu8hdp5E-eWEgMhfMigpZ2qpNCkKTdxpeVE/edit#slide=id.p)
