### ISSUE TITLE
Determine what roles we're hiring into for the summer

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#91]
cc @lourdesvera @saraannwylie

┆Issue is synchronized with this [Trello card](https://trello.com/c/bPmiri2L)

**Comment by Frijol** [comment]
related to https://github.com/edgi-govdata-archiving/EEW_Planning/issues/103

**Comment by lourdesvera** [comment]
Is this pretty much done?

**Comment by Frijol** [comment]
Pretty sure we did this!
* Notebooks summer research assistant
* Research & contextualization summer research assistant
* Storytelling & community organizing summer research assistant
* Visualization for course credit
