### ISSUE TITLE
Make a directory of people in the readme

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#92]
Link to readme: https://github.com/edgi-govdata-archiving/EEW_Planning

In the context of this as (a) an open source project and (b) a project with many new contributors, it would be helpful to explicitly spell out who is who, and what they're responsible for such that they can be tagged appropriately

┆Issue is synchronized with this [Trello card](https://trello.com/c/d6lO2dZ6)

**Comment by Frijol** [comment]
Here is what I'm thinking:

| Name | Github | Area of responsibility/Tag me on conversations about... |
| ------|--------|----------------------|
| Sara Wylie | @saraannwylie | (add your description) |
| Lourdes Vera | @lourdesvera | |
| EDGI Comms (Kelly) | @EDGI-Comms| |
| Cole Alder | @calderEDJ | |
| Casey Greenleaf | @crgreenleaf | |
| Steve Hansen | @shansen5 | |
| Chris Sellers | @csellers9 | |
| Eric Nost | @ericnost  | |
| Kelsey Breseman | @Frijol |  |

etc

Not sure what that last column should be since we have kinda handwavey roles but even just having a list of github handles paired to names is helpful

**Comment by lourdesvera** [comment]
I think that's a good idea. This is really where we can delineate roles too

**Comment by lourdesvera** [comment]
This is related to https://github.com/edgi-govdata-archiving/EEW_Planning/issues/114

**Comment by lourdesvera** [comment]
People need to add their roles

**Comment by lourdesvera** [comment]
Link to readme: https://github.com/edgi-govdata-archiving/EEW_Planning


@edgi-comms
@calderedj
@cgreenleaf
@shansen5
@csellers9
@sunggheel
@pstdenis
@danpascucci

Please fill in your roles in relation to this project. Thanks!

**Comment by lourdesvera** [comment]
I'm closing this as most people have added themselves.
