### ISSUE TITLE
Update the EDGI Handbook for EEW hiring

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#93]
[WIP here](https://docs.google.com/document/d/1Wg6Bw3UEwi50t2bbsQmgzaY53hafbDr_sk5Vp1IV07U/edit?pli=1#)

* [x] Org chart in [How We are Structured](https://docs.google.com/document/d/1Wg6Bw3UEwi50t2bbsQmgzaY53hafbDr_sk5Vp1IV07U/edit?pli=1#heading=h.el97iqkfvluj) should get to something that feels at least a bit complete https://github.com/edgi-govdata-archiving/EEW_Planning/issues/132
* [x] Onboarding Process [section](https://docs.google.com/document/d/1Wg6Bw3UEwi50t2bbsQmgzaY53hafbDr_sk5Vp1IV07U/edit?pli=1#heading=h.jefcvyeaawbu) related: https://github.com/edgi-govdata-archiving/EEW_Planning/issues/89
* [x] [Guide to meetings](https://docs.google.com/document/d/1Wg6Bw3UEwi50t2bbsQmgzaY53hafbDr_sk5Vp1IV07U/edit?pli=1#heading=h.gcea8xis5dd4)
* [x] [Conflict resolution](https://docs.google.com/document/d/1Wg6Bw3UEwi50t2bbsQmgzaY53hafbDr_sk5Vp1IV07U/edit?pli=1#heading=h.r6azyanl8djy) section
* [x] Slack channel names added to [Working groups](https://docs.google.com/document/d/1Wg6Bw3UEwi50t2bbsQmgzaY53hafbDr_sk5Vp1IV07U/edit?pli=1#heading=h.7xa1fvx6gtqu) section

┆Issue is synchronized with this [Trello card](https://trello.com/c/CNBEa856)

**Comment by Frijol** [comment]
I think @EDGI-Comms is working on this at the moment

**Comment by lourdesvera** [comment]
@EDGI-Comms do you need help with this?

**Comment by EDGI-Comms** [comment]
@lourdesvera Yes that would be great! I haven't had time to look at it. But I will add my comments today from the perspective of a person recently on-boarded.

**Comment by EDGI-Comms** [comment]
@Frijol I've added a few comments to the Handbook. Please let me know if you need more feedback or would like me to add any sections. This doc is amazing though. I wish I knew about it when I onboarded! Well done! :-)

**Comment by Frijol** [comment]
@lourdesvera can I ping this to you as a next reviewer during this week's sprint?

**Comment by lourdesvera** [comment]
We also need to incorporate the EDGI Protocol somehow? I'm confused that the difference between the Handbook and Protocol 

https://docs.google.com/document/d/1ji0KcSpBvaxceFAsC6uMsX9A-utiyTVPQUow9v0Oq4o/edit#heading=h.em3jx42bnrkg

**Comment by Frijol** [comment]
The difference at least in my head is that the Protocol is more like our Constitution, vs the Handbook is more of a helpful guide. Handbook describes things but doesn't create or define any rules. It's accessible but not a source of truth. Protocol actually is the rulebook. Important, not necessarily the most accessible, shouldn't have how-to content (...which I know is itself a bit in flux) but rather sets out/is source of truth for our foundational philosophies and agreements.

Does that sound right to you? Should def at least ref Protocol from Handbook

**Comment by Frijol** [comment]
Taking a look at this now

**Comment by Frijol** [comment]
I think this doc doesn't need to be 100% polished to be usable – & in fact it is probably already better than not having it for any new members.

For summer hiring, here's what I think should get more complete:
* [ ] Org chart in [How We are Structured](https://docs.google.com/document/d/1Wg6Bw3UEwi50t2bbsQmgzaY53hafbDr_sk5Vp1IV07U/edit?pli=1#heading=h.el97iqkfvluj) should get to something that feels at least a bit complete
* [ ] Onboarding Process [section](https://docs.google.com/document/d/1Wg6Bw3UEwi50t2bbsQmgzaY53hafbDr_sk5Vp1IV07U/edit?pli=1#heading=h.jefcvyeaawbu)
* [ ] [Guide to meetings](https://docs.google.com/document/d/1Wg6Bw3UEwi50t2bbsQmgzaY53hafbDr_sk5Vp1IV07U/edit?pli=1#heading=h.gcea8xis5dd4)
* [ ] [Conflict resolution](https://docs.google.com/document/d/1Wg6Bw3UEwi50t2bbsQmgzaY53hafbDr_sk5Vp1IV07U/edit?pli=1#heading=h.r6azyanl8djy) section
* [ ] Slack channel names added to [Working groups](https://docs.google.com/document/d/1Wg6Bw3UEwi50t2bbsQmgzaY53hafbDr_sk5Vp1IV07U/edit?pli=1#heading=h.7xa1fvx6gtqu) section

I don't think we need to resolve all comments & suggestions before use; in fact it may be useful to have a few so that new people feel ok interacting with the doc in that way

**Comment by Frijol** [comment]
@saraannwylie @lourdesvera @ericnost @calderEDJ @crgreenleaf what do you think of the above checklist for sufficient completeness for summer hires to start?

**Comment by ericnost** [comment]
FWIW, I'll be working on this Sunday...

**Comment by ericnost** [comment]
My review:

- Org chart in How We are Structured (already done)
- Onboarding Process section related: #89
- - I couldn't find much to tweak here, but happy to give it another go with more direction. It reads as if it's directed towards new volunteer members rather than interns/contractors, but that's probably fine.
- Guide to meetings
- - There is (no longer?) any Guide to meetings section. The link takes me to the SCC section. What should be done here?
- Conflict resolution section.
- - I think others have noted that the Conflict Committee membership description probably needs updating....but I think we have to re-form the committee first.
- Slack channel names added to Working groups section (already done)

@Frijol @lourdesvera

**Comment by Frijol** [comment]
Thanks all for working on this! I think we've reached a 1.0 edition 🎊 
Agreed re re-forming the conflict committee (something to bring up next all-EDGI?)
